deploymentType: NetworkShare
credentialsId: brierley-jenkinsuat
artifactShare: '\\cy2cdeploy01.brierley.com\Builds'
artifactPath: AmericanEagle\A-Line
organization: AmericanEagle
environment: StageBLine
navigatorUrl: https://aeoadmin.brierleyweb.net/
schedulerUrl: net.tcp://cypwbs303.brierleyweb.com:9543/LWJobScheduler
navigatorInstanceId: aeo
deployRemoteAssemblyMode: NugetBatchProject
confluenceDeploymentReportId: 975339737
projects:
  LWIntgrService:
    websiteName: stage-apiaerewards-bline.brierley.com
    deployPath: E$\wwwroot\stage-apiaerewards-bline
    targetHosts:
    - cy2twbs20.brierley.com
  CustomerServicePortal:
    websiteName: stage-csaerewards-bline.brierley.com
    deployPath: E$\wwwroot\stage-csaerewards-bline
    targetHosts:
    - cy2twbs20.brierley.com
    skipSkinDirectory: true
  DAP:
    deployPath: E$\AmericanEagleBline\Processors\DAP
    targetHosts:
    - cy2tapp01.brierley.com
  RulesProcessor:
    deployPath: E$\AmericanEagleBline\Processors\RulesProcessor
    targetHosts:
    - cy2tapp01.brierley.com
  FileCountUtility:
    deployPath: E$\AmericanEagleBline\Utilities\FileCountUtility
    targetHosts:
    - cy2tapp01.brierley.com
