//------------------------------------------------------------------------------
// <autogenerated>
//     This code was generated by LoyaltyWare.
//
//     Changes to this file may cause incorrect behavior and will be lost if 
//     the code is regenerated.
// </autogenerated>
//------------------------------------------------------------------------------

package com.brierley.loyaltyware.clientlib.domainmodel.client;

import java.util.Date;

import com.brierley.loyaltyware.clientlib.annotations.*;
import com.brierley.loyaltyware.clientlib.domainmodel.framework.Member;
import com.brierley.loyaltyware.clientlib.domainmodel.framework.VirtualCard;

public class AccountActivityDetailsStruct {
	// property: ItemDescription
	      								
	private String ItemDescription;
	public 	String getItemDescription() {
		return this.ItemDescription;
	}
	public 	void setItemDescription(String ItemDescription) {
		this.ItemDescription = ItemDescription;
	}	
				
	// property: Quantity
	      								
	private Integer Quantity;
	public 	Integer getQuantity() {
		return this.Quantity;
	}
	public 	void setQuantity(Integer Quantity) {
		this.Quantity = Quantity;
	}	
				
	// property: SaleAmount
	@LWIsRequired       								
	private java.math.BigDecimal SaleAmount;
	public 	java.math.BigDecimal getSaleAmount() {
		return this.SaleAmount;
	}
	public 	void setSaleAmount(java.math.BigDecimal SaleAmount) {
		this.SaleAmount = SaleAmount;
	}	
				
	// property: ClassDescription
	      								
	private String ClassDescription;
	public 	String getClassDescription() {
		return this.ClassDescription;
	}
	public 	void setClassDescription(String ClassDescription) {
		this.ClassDescription = ClassDescription;
	}	
				
	// property: ClassCode
	      								
	private String ClassCode;
	public 	String getClassCode() {
		return this.ClassCode;
	}
	public 	void setClassCode(String ClassCode) {
		this.ClassCode = ClassCode;
	}	
				
	// property: PointsHistory
	      								
	private PointsHistoryStruct[] PointsHistory;
	public 	PointsHistoryStruct[] getPointsHistory() {
		return this.PointsHistory;
	}
	public 	void setPointsHistory(PointsHistoryStruct[] PointsHistory) {
		this.PointsHistory = PointsHistory;
	}	
				
	// property: AdditionalAttributes
	      								
	private AdditionalAttributesStruct[] AdditionalAttributes;
	public 	AdditionalAttributesStruct[] getAdditionalAttributes() {
		return this.AdditionalAttributes;
	}
	public 	void setAdditionalAttributes(AdditionalAttributesStruct[] AdditionalAttributes) {
		this.AdditionalAttributes = AdditionalAttributes;
	}	
				
}
