//------------------------------------------------------------------------------
// <autogenerated>
//     This code was generated by LoyaltyWare.
//
//     Changes to this file may cause incorrect behavior and will be lost if 
//     the code is regenerated.
// </autogenerated>
//------------------------------------------------------------------------------

package com.brierley.loyaltyware.clientlib.domainmodel.client;

import java.util.Date;

import com.brierley.loyaltyware.clientlib.annotations.*;
import com.brierley.loyaltyware.clientlib.domainmodel.framework.Member;
import com.brierley.loyaltyware.clientlib.domainmodel.framework.VirtualCard;

public class AddMemberRewardsOut {
	// property: CurrencyBalance
	@LWIsRequired       								
	private java.math.BigDecimal CurrencyBalance;
	public 	java.math.BigDecimal getCurrencyBalance() {
		return this.CurrencyBalance;
	}
	public 	void setCurrencyBalance(java.math.BigDecimal CurrencyBalance) {
		this.CurrencyBalance = CurrencyBalance;
	}	
				
	// property: MemberRewardID
	      								
	private Long MemberRewardID;
	public 	Long getMemberRewardID() {
		return this.MemberRewardID;
	}
	public 	void setMemberRewardID(Long MemberRewardID) {
		this.MemberRewardID = MemberRewardID;
	}	
				
	// property: OrderNumber
	      								
	private String OrderNumber;
	public 	String getOrderNumber() {
		return this.OrderNumber;
	}
	public 	void setOrderNumber(String OrderNumber) {
		this.OrderNumber = OrderNumber;
	}	
				
}
