//------------------------------------------------------------------------------
// <autogenerated>
//     This code was generated by LoyaltyWare.
//
//     Changes to this file may cause incorrect behavior and will be lost if 
//     the code is regenerated.
// </autogenerated>
//------------------------------------------------------------------------------

package com.brierley.loyaltyware.clientlib.domainmodel.client;

import java.util.Date;

import com.brierley.loyaltyware.clientlib.annotations.*;
import com.brierley.loyaltyware.clientlib.domainmodel.framework.Member;
import com.brierley.loyaltyware.clientlib.domainmodel.framework.VirtualCard;

public class AEAutoRegisterIn {
	// property: FirstName
	      								
	private String FirstName;
	public 	String getFirstName() {
		return this.FirstName;
	}
	public 	void setFirstName(String FirstName) {
		this.FirstName = FirstName;
	}	
				
	// property: LastName
	      								
	private String LastName;
	public 	String getLastName() {
		return this.LastName;
	}
	public 	void setLastName(String LastName) {
		this.LastName = LastName;
	}	
				
	// property: LoyaltyNumber
	      								
	private String LoyaltyNumber;
	public 	String getLoyaltyNumber() {
		return this.LoyaltyNumber;
	}
	public 	void setLoyaltyNumber(String LoyaltyNumber) {
		this.LoyaltyNumber = LoyaltyNumber;
	}	
				
	// property: EmailAddress
	      								
	private String EmailAddress;
	public 	String getEmailAddress() {
		return this.EmailAddress;
	}
	public 	void setEmailAddress(String EmailAddress) {
		this.EmailAddress = EmailAddress;
	}	
				
}
