//------------------------------------------------------------------------------
// <autogenerated>
//     This code was generated by LoyaltyWare.
//
//     Changes to this file may cause incorrect behavior and will be lost if 
//     the code is regenerated.
// </autogenerated>
//------------------------------------------------------------------------------

package com.brierley.loyaltyware.clientlib.domainmodel.client;

import java.util.Date;

import com.brierley.loyaltyware.clientlib.annotations.*;
import com.brierley.loyaltyware.clientlib.domainmodel.framework.Member;
import com.brierley.loyaltyware.clientlib.domainmodel.framework.VirtualCard;

public class AEPOSGetAccountActivityOut {
	// property: LoyaltyNumber
	@LWIsRequired       								
	private String LoyaltyNumber;
	public 	String getLoyaltyNumber() {
		return this.LoyaltyNumber;
	}
	public 	void setLoyaltyNumber(String LoyaltyNumber) {
		this.LoyaltyNumber = LoyaltyNumber;
	}	
				
	// property: TotalPageCount
	      								
	private Integer TotalPageCount;
	public 	Integer getTotalPageCount() {
		return this.TotalPageCount;
	}
	public 	void setTotalPageCount(Integer TotalPageCount) {
		this.TotalPageCount = TotalPageCount;
	}	
				
	// property: StartingPoints
	      								
	private String StartingPoints;
	public 	String getStartingPoints() {
		return this.StartingPoints;
	}
	public 	void setStartingPoints(String StartingPoints) {
		this.StartingPoints = StartingPoints;
	}	
				
	// property: BasicPoints
	      								
	private String BasicPoints;
	public 	String getBasicPoints() {
		return this.BasicPoints;
	}
	public 	void setBasicPoints(String BasicPoints) {
		this.BasicPoints = BasicPoints;
	}	
				
	// property: BonusPoints
	      								
	private String BonusPoints;
	public 	String getBonusPoints() {
		return this.BonusPoints;
	}
	public 	void setBonusPoints(String BonusPoints) {
		this.BonusPoints = BonusPoints;
	}	
				
	// property: TotalPoints
	      								
	private String TotalPoints;
	public 	String getTotalPoints() {
		return this.TotalPoints;
	}
	public 	void setTotalPoints(String TotalPoints) {
		this.TotalPoints = TotalPoints;
	}	
				
	// property: RewardLevel
	      								
	private String RewardLevel;
	public 	String getRewardLevel() {
		return this.RewardLevel;
	}
	public 	void setRewardLevel(String RewardLevel) {
		this.RewardLevel = RewardLevel;
	}	
				
	// property: DollarRewardMember
	      								
	private String DollarRewardMember;
	public 	String getDollarRewardMember() {
		return this.DollarRewardMember;
	}
	public 	void setDollarRewardMember(String DollarRewardMember) {
		this.DollarRewardMember = DollarRewardMember;
	}	
				
	// property: StartDate
	      								
	private String StartDate;
	public 	String getStartDate() {
		return this.StartDate;
	}
	public 	void setStartDate(String StartDate) {
		this.StartDate = StartDate;
	}	
				
	// property: EndDate
	      								
	private String EndDate;
	public 	String getEndDate() {
		return this.EndDate;
	}
	public 	void setEndDate(String EndDate) {
		this.EndDate = EndDate;
	}	
				
	// property: TransactionHeaders
	      								
	private TransactionHeadersStruct[] TransactionHeaders;
	public 	TransactionHeadersStruct[] getTransactionHeaders() {
		return this.TransactionHeaders;
	}
	public 	void setTransactionHeaders(TransactionHeadersStruct[] TransactionHeaders) {
		this.TransactionHeaders = TransactionHeaders;
	}	
				
}
