//------------------------------------------------------------------------------
// <autogenerated>
//     This code was generated by LoyaltyWare.
//
//     Changes to this file may cause incorrect behavior and will be lost if 
//     the code is regenerated.
// </autogenerated>
//------------------------------------------------------------------------------

package com.brierley.loyaltyware.clientlib.domainmodel.client;

import java.util.Date;

import com.brierley.loyaltyware.clientlib.annotations.*;
import com.brierley.loyaltyware.clientlib.domainmodel.framework.Member;
import com.brierley.loyaltyware.clientlib.domainmodel.framework.VirtualCard;

public class AERequestPointOnlineIn {
	// property: LoyaltyNumber
	      								
	private String LoyaltyNumber;
	public 	String getLoyaltyNumber() {
		return this.LoyaltyNumber;
	}
	public 	void setLoyaltyNumber(String LoyaltyNumber) {
		this.LoyaltyNumber = LoyaltyNumber;
	}	
				
	// property: OrderNumber
	      								
	private String OrderNumber;
	public 	String getOrderNumber() {
		return this.OrderNumber;
	}
	public 	void setOrderNumber(String OrderNumber) {
		this.OrderNumber = OrderNumber;
	}	
				
	// property: OrderAmount
	      								
	private String OrderAmount;
	public 	String getOrderAmount() {
		return this.OrderAmount;
	}
	public 	void setOrderAmount(String OrderAmount) {
		this.OrderAmount = OrderAmount;
	}	
				
}
