//------------------------------------------------------------------------------
// <autogenerated>
//     This code was generated by LoyaltyWare.
//
//     Changes to this file may cause incorrect behavior and will be lost if 
//     the code is regenerated.
// </autogenerated>
//------------------------------------------------------------------------------

package com.brierley.loyaltyware.clientlib.domainmodel.client;

import java.util.Date;

import com.brierley.loyaltyware.clientlib.annotations.*;
import com.brierley.loyaltyware.clientlib.domainmodel.framework.Member;
import com.brierley.loyaltyware.clientlib.domainmodel.framework.VirtualCard;

public class AERequestPointStoreIn {
	// property: LoyaltyNumber
	      								
	private String LoyaltyNumber;
	public 	String getLoyaltyNumber() {
		return this.LoyaltyNumber;
	}
	public 	void setLoyaltyNumber(String LoyaltyNumber) {
		this.LoyaltyNumber = LoyaltyNumber;
	}	
				
	// property: RegisterNumber
	      								
	private String RegisterNumber;
	public 	String getRegisterNumber() {
		return this.RegisterNumber;
	}
	public 	void setRegisterNumber(String RegisterNumber) {
		this.RegisterNumber = RegisterNumber;
	}	
				
	// property: StoreNumber
	      								
	private String StoreNumber;
	public 	String getStoreNumber() {
		return this.StoreNumber;
	}
	public 	void setStoreNumber(String StoreNumber) {
		this.StoreNumber = StoreNumber;
	}	
				
	// property: TotalPayment
	      								
	private String TotalPayment;
	public 	String getTotalPayment() {
		return this.TotalPayment;
	}
	public 	void setTotalPayment(String TotalPayment) {
		this.TotalPayment = TotalPayment;
	}	
				
	// property: TransactionDate
	      								
	private String TransactionDate;
	public 	String getTransactionDate() {
		return this.TransactionDate;
	}
	public 	void setTransactionDate(String TransactionDate) {
		this.TransactionDate = TransactionDate;
	}	
				
	// property: TransactionNumber
	      								
	private String TransactionNumber;
	public 	String getTransactionNumber() {
		return this.TransactionNumber;
	}
	public 	void setTransactionNumber(String TransactionNumber) {
		this.TransactionNumber = TransactionNumber;
	}	
				
}
