//------------------------------------------------------------------------------
// <autogenerated>
//     This code was generated by LoyaltyWare.
//
//     Changes to this file may cause incorrect behavior and will be lost if 
//     the code is regenerated.
// </autogenerated>
//------------------------------------------------------------------------------

package com.brierley.loyaltyware.clientlib.domainmodel.client;

import java.util.Date;

import com.brierley.loyaltyware.clientlib.annotations.*;
import com.brierley.loyaltyware.clientlib.domainmodel.framework.Member;
import com.brierley.loyaltyware.clientlib.domainmodel.framework.VirtualCard;

public class AERegisterMemberOut {
	// property: LoyaltyNumber
	@LWIsRequired       								
	private String LoyaltyNumber;
	public 	String getLoyaltyNumber() {
		return this.LoyaltyNumber;
	}
	public 	void setLoyaltyNumber(String LoyaltyNumber) {
		this.LoyaltyNumber = LoyaltyNumber;
	}	
				
	// property: BaseBrand
	      								
	private String BaseBrand;
	public 	String getBaseBrand() {
		return this.BaseBrand;
	}
	public 	void setBaseBrand(String BaseBrand) {
		this.BaseBrand = BaseBrand;
	}	
				
}
