//------------------------------------------------------------------------------
// <autogenerated>
//     This code was generated by LoyaltyWare.
//
//     Changes to this file may cause incorrect behavior and will be lost if 
//     the code is regenerated.
// </autogenerated>
//------------------------------------------------------------------------------

package com.brierley.loyaltyware.clientlib.domainmodel.client;

import java.util.Date;
import com.brierley.loyaltyware.clientlib.annotations.*;
import com.brierley.loyaltyware.clientlib.domainmodel.LWClientDataObject;

public class BraReasonCodes extends LWClientDataObject {			    
	// property: ReasonCode
	
	private Long ReasonCode;
	public 	Long getReasonCode() {
		return this.ReasonCode;
	}
	public 	void setReasonCode(Long reasoncode) {
		this.ReasonCode = reasoncode;
	}

	// property: EffectiveStartDate
	
	private Date EffectiveStartDate;
	public 	Date getEffectiveStartDate() {
		return this.EffectiveStartDate;
	}
	public 	void setEffectiveStartDate(Date effectivestartdate) {
		this.EffectiveStartDate = effectivestartdate;
	}

	// property: EffectiveEndDate
	
	private Date EffectiveEndDate;
	public 	Date getEffectiveEndDate() {
		return this.EffectiveEndDate;
	}
	public 	void setEffectiveEndDate(Date effectiveenddate) {
		this.EffectiveEndDate = effectiveenddate;
	}

	// property: MailFilePullDate
	
	private Date MailFilePullDate;
	public 	Date getMailFilePullDate() {
		return this.MailFilePullDate;
	}
	public 	void setMailFilePullDate(Date mailfilepulldate) {
		this.MailFilePullDate = mailfilepulldate;
	}

}