//------------------------------------------------------------------------------
// <autogenerated>
//     This code was generated by LoyaltyWare.
//
//     Changes to this file may cause incorrect behavior and will be lost if 
//     the code is regenerated.
// </autogenerated>
//------------------------------------------------------------------------------

package com.brierley.loyaltyware.clientlib.domainmodel.client;

import java.util.Date;

import com.brierley.loyaltyware.clientlib.annotations.*;
import com.brierley.loyaltyware.clientlib.domainmodel.framework.Member;
import com.brierley.loyaltyware.clientlib.domainmodel.framework.VirtualCard;

public class CancelCardIn {
	// property: CardID
	@LWIsRequired @LWStringLength(255)       								
	private String CardID;
	public 	String getCardID() {
		return this.CardID;
	}
	public 	void setCardID(String CardID) {
		this.CardID = CardID;
	}	
				
	// property: EffectiveDate
	      								
	private Date EffectiveDate;
	public 	Date getEffectiveDate() {
		return this.EffectiveDate;
	}
	public 	void setEffectiveDate(Date EffectiveDate) {
		this.EffectiveDate = EffectiveDate;
	}	
				
	// property: UpdateCardStatusReason
	@LWStringLength(255)       								
	private String UpdateCardStatusReason;
	public 	String getUpdateCardStatusReason() {
		return this.UpdateCardStatusReason;
	}
	public 	void setUpdateCardStatusReason(String UpdateCardStatusReason) {
		this.UpdateCardStatusReason = UpdateCardStatusReason;
	}	
				
	// property: DeactivateMember
	      								
	private Boolean DeactivateMember;
	public 	Boolean getDeactivateMember() {
		return this.DeactivateMember;
	}
	public 	void setDeactivateMember(Boolean DeactivateMember) {
		this.DeactivateMember = DeactivateMember;
	}	
				
}
