//------------------------------------------------------------------------------
// <autogenerated>
//     This code was generated by LoyaltyWare.
//
//     Changes to this file may cause incorrect behavior and will be lost if 
//     the code is regenerated.
// </autogenerated>
//------------------------------------------------------------------------------

package com.brierley.loyaltyware.clientlib.domainmodel.client;

import java.util.Date;

import com.brierley.loyaltyware.clientlib.annotations.*;
import com.brierley.loyaltyware.clientlib.domainmodel.framework.Member;
import com.brierley.loyaltyware.clientlib.domainmodel.framework.VirtualCard;

public class CSNoteStruct {
	// property: Note
	      								
	private String Note;
	public 	String getNote() {
		return this.Note;
	}
	public 	void setNote(String Note) {
		this.Note = Note;
	}	
				
	// property: CreatedBy
	      								
	private Long CreatedBy;
	public 	Long getCreatedBy() {
		return this.CreatedBy;
	}
	public 	void setCreatedBy(Long CreatedBy) {
		this.CreatedBy = CreatedBy;
	}	
				
	// property: CreateDate
	      								
	private Date CreateDate;
	public 	Date getCreateDate() {
		return this.CreateDate;
	}
	public 	void setCreateDate(Date CreateDate) {
		this.CreateDate = CreateDate;
	}	
				
}
