//------------------------------------------------------------------------------
// <autogenerated>
//     This code was generated by LoyaltyWare.
//
//     Changes to this file may cause incorrect behavior and will be lost if 
//     the code is regenerated.
// </autogenerated>
//------------------------------------------------------------------------------

package com.brierley.loyaltyware.clientlib.domainmodel.client;

import java.util.Date;

import com.brierley.loyaltyware.clientlib.annotations.*;
import com.brierley.loyaltyware.clientlib.domainmodel.framework.Member;
import com.brierley.loyaltyware.clientlib.domainmodel.framework.VirtualCard;

public class DeactivateMemberIn {
	// property: MemberIdentity
	@LWIsRequired       								
	private String MemberIdentity;
	public 	String getMemberIdentity() {
		return this.MemberIdentity;
	}
	public 	void setMemberIdentity(String MemberIdentity) {
		this.MemberIdentity = MemberIdentity;
	}	
				
	// property: EffectiveDate
	      								
	private Date EffectiveDate;
	public 	Date getEffectiveDate() {
		return this.EffectiveDate;
	}
	public 	void setEffectiveDate(Date EffectiveDate) {
		this.EffectiveDate = EffectiveDate;
	}	
				
	// property: UpdateMemberStatusReason
	@LWStringLength(255)       								
	private String UpdateMemberStatusReason;
	public 	String getUpdateMemberStatusReason() {
		return this.UpdateMemberStatusReason;
	}
	public 	void setUpdateMemberStatusReason(String UpdateMemberStatusReason) {
		this.UpdateMemberStatusReason = UpdateMemberStatusReason;
	}	
				
	// property: DeactivateActiveCards
	      								
	private Boolean DeactivateActiveCards;
	public 	Boolean getDeactivateActiveCards() {
		return this.DeactivateActiveCards;
	}
	public 	void setDeactivateActiveCards(Boolean DeactivateActiveCards) {
		this.DeactivateActiveCards = DeactivateActiveCards;
	}	
				
	// property: ExpirePoints
	      								
	private Boolean ExpirePoints;
	public 	Boolean getExpirePoints() {
		return this.ExpirePoints;
	}
	public 	void setExpirePoints(Boolean ExpirePoints) {
		this.ExpirePoints = ExpirePoints;
	}	
				
	// property: CancelTiers
	      								
	private Boolean CancelTiers;
	public 	Boolean getCancelTiers() {
		return this.CancelTiers;
	}
	public 	void setCancelTiers(Boolean CancelTiers) {
		this.CancelTiers = CancelTiers;
	}	
				
	// property: CancelRewards
	      								
	private Boolean CancelRewards;
	public 	Boolean getCancelRewards() {
		return this.CancelRewards;
	}
	public 	void setCancelRewards(Boolean CancelRewards) {
		this.CancelRewards = CancelRewards;
	}	
				
	// property: CancelPromotions
	      								
	private Boolean CancelPromotions;
	public 	Boolean getCancelPromotions() {
		return this.CancelPromotions;
	}
	public 	void setCancelPromotions(Boolean CancelPromotions) {
		this.CancelPromotions = CancelPromotions;
	}	
				
	// property: CancelBonuses
	      								
	private Boolean CancelBonuses;
	public 	Boolean getCancelBonuses() {
		return this.CancelBonuses;
	}
	public 	void setCancelBonuses(Boolean CancelBonuses) {
		this.CancelBonuses = CancelBonuses;
	}	
				
	// property: CancelCoupons
	      								
	private Boolean CancelCoupons;
	public 	Boolean getCancelCoupons() {
		return this.CancelCoupons;
	}
	public 	void setCancelCoupons(Boolean CancelCoupons) {
		this.CancelCoupons = CancelCoupons;
	}	
				
}
