//------------------------------------------------------------------------------
// <autogenerated>
//     This code was generated by LoyaltyWare.
//
//     Changes to this file may cause incorrect behavior and will be lost if 
//     the code is regenerated.
// </autogenerated>
//------------------------------------------------------------------------------

package com.brierley.loyaltyware.clientlib.domainmodel.client;

import java.util.Date;

import com.brierley.loyaltyware.clientlib.annotations.*;
import com.brierley.loyaltyware.clientlib.domainmodel.framework.Member;
import com.brierley.loyaltyware.clientlib.domainmodel.framework.VirtualCard;

public class GetAccountActivitySummaryOut {
	// property: AccountActivitySummary
	      								
	private AccountActivitySummaryStruct[] AccountActivitySummary;
	public 	AccountActivitySummaryStruct[] getAccountActivitySummary() {
		return this.AccountActivitySummary;
	}
	public 	void setAccountActivitySummary(AccountActivitySummaryStruct[] AccountActivitySummary) {
		this.AccountActivitySummary = AccountActivitySummary;
	}	
				
	// property: OtherPointsHistory
	      								
	private OtherPointsHistoryStruct[] OtherPointsHistory;
	public 	OtherPointsHistoryStruct[] getOtherPointsHistory() {
		return this.OtherPointsHistory;
	}
	public 	void setOtherPointsHistory(OtherPointsHistoryStruct[] OtherPointsHistory) {
		this.OtherPointsHistory = OtherPointsHistory;
	}	
				
}
