//------------------------------------------------------------------------------
// <autogenerated>
//     This code was generated by LoyaltyWare.
//
//     Changes to this file may cause incorrect behavior and will be lost if 
//     the code is regenerated.
// </autogenerated>
//------------------------------------------------------------------------------

package com.brierley.loyaltyware.clientlib.domainmodel.client;

import java.util.Date;

import com.brierley.loyaltyware.clientlib.annotations.*;
import com.brierley.loyaltyware.clientlib.domainmodel.framework.Member;
import com.brierley.loyaltyware.clientlib.domainmodel.framework.VirtualCard;

public class GetAccountSummaryOut {
	// property: CurrencyBalance
	@LWIsRequired       								
	private java.math.BigDecimal CurrencyBalance;
	public 	java.math.BigDecimal getCurrencyBalance() {
		return this.CurrencyBalance;
	}
	public 	void setCurrencyBalance(java.math.BigDecimal CurrencyBalance) {
		this.CurrencyBalance = CurrencyBalance;
	}	
				
	// property: MemberStatus
	@LWIsRequired       								
	private String MemberStatus;
	public 	String getMemberStatus() {
		return this.MemberStatus;
	}
	public 	void setMemberStatus(String MemberStatus) {
		this.MemberStatus = MemberStatus;
	}	
				
	// property: MemberAddDate
	@LWIsRequired       								
	private Date MemberAddDate;
	public 	Date getMemberAddDate() {
		return this.MemberAddDate;
	}
	public 	void setMemberAddDate(Date MemberAddDate) {
		this.MemberAddDate = MemberAddDate;
	}	
				
	// property: CurrentTierName
	      								
	private String CurrentTierName;
	public 	String getCurrentTierName() {
		return this.CurrentTierName;
	}
	public 	void setCurrentTierName(String CurrentTierName) {
		this.CurrentTierName = CurrentTierName;
	}	
				
	// property: CurrentTierExpirationDate
	      								
	private Date CurrentTierExpirationDate;
	public 	Date getCurrentTierExpirationDate() {
		return this.CurrentTierExpirationDate;
	}
	public 	void setCurrentTierExpirationDate(Date CurrentTierExpirationDate) {
		this.CurrentTierExpirationDate = CurrentTierExpirationDate;
	}	
				
	// property: CurrencyToNextTier
	      								
	private java.math.BigDecimal CurrencyToNextTier;
	public 	java.math.BigDecimal getCurrencyToNextTier() {
		return this.CurrencyToNextTier;
	}
	public 	void setCurrencyToNextTier(java.math.BigDecimal CurrencyToNextTier) {
		this.CurrencyToNextTier = CurrencyToNextTier;
	}	
				
	// property: CurrencyToNextReward
	      								
	private java.math.BigDecimal CurrencyToNextReward;
	public 	java.math.BigDecimal getCurrencyToNextReward() {
		return this.CurrencyToNextReward;
	}
	public 	void setCurrencyToNextReward(java.math.BigDecimal CurrencyToNextReward) {
		this.CurrencyToNextReward = CurrencyToNextReward;
	}	
				
	// property: LastActivityDate
	      								
	private Date LastActivityDate;
	public 	Date getLastActivityDate() {
		return this.LastActivityDate;
	}
	public 	void setLastActivityDate(Date LastActivityDate) {
		this.LastActivityDate = LastActivityDate;
	}	
				
}
