//------------------------------------------------------------------------------
// <autogenerated>
//     This code was generated by LoyaltyWare.
//
//     Changes to this file may cause incorrect behavior and will be lost if 
//     the code is regenerated.
// </autogenerated>
//------------------------------------------------------------------------------

package com.brierley.loyaltyware.clientlib.domainmodel.client;

import java.util.Date;

import com.brierley.loyaltyware.clientlib.annotations.*;
import com.brierley.loyaltyware.clientlib.domainmodel.framework.Member;
import com.brierley.loyaltyware.clientlib.domainmodel.framework.VirtualCard;

public class GetLoyaltyProfileStruct {
	// property: LoyaltyNumber
	      								
	private String LoyaltyNumber;
	public 	String getLoyaltyNumber() {
		return this.LoyaltyNumber;
	}
	public 	void setLoyaltyNumber(String LoyaltyNumber) {
		this.LoyaltyNumber = LoyaltyNumber;
	}	
				
	// property: FirstName
	      								
	private String FirstName;
	public 	String getFirstName() {
		return this.FirstName;
	}
	public 	void setFirstName(String FirstName) {
		this.FirstName = FirstName;
	}	
				
	// property: LastName
	      								
	private String LastName;
	public 	String getLastName() {
		return this.LastName;
	}
	public 	void setLastName(String LastName) {
		this.LastName = LastName;
	}	
				
	// property: AddressLineOne
	      								
	private String AddressLineOne;
	public 	String getAddressLineOne() {
		return this.AddressLineOne;
	}
	public 	void setAddressLineOne(String AddressLineOne) {
		this.AddressLineOne = AddressLineOne;
	}	
				
	// property: AddressLineTwo
	      								
	private String AddressLineTwo;
	public 	String getAddressLineTwo() {
		return this.AddressLineTwo;
	}
	public 	void setAddressLineTwo(String AddressLineTwo) {
		this.AddressLineTwo = AddressLineTwo;
	}	
				
	// property: City
	      								
	private String City;
	public 	String getCity() {
		return this.City;
	}
	public 	void setCity(String City) {
		this.City = City;
	}	
				
	// property: State
	      								
	private String State;
	public 	String getState() {
		return this.State;
	}
	public 	void setState(String State) {
		this.State = State;
	}	
				
	// property: PostalCode
	      								
	private String PostalCode;
	public 	String getPostalCode() {
		return this.PostalCode;
	}
	public 	void setPostalCode(String PostalCode) {
		this.PostalCode = PostalCode;
	}	
				
	// property: Country
	      								
	private String Country;
	public 	String getCountry() {
		return this.Country;
	}
	public 	void setCountry(String Country) {
		this.Country = Country;
	}	
				
	// property: HomePhone
	      								
	private String HomePhone;
	public 	String getHomePhone() {
		return this.HomePhone;
	}
	public 	void setHomePhone(String HomePhone) {
		this.HomePhone = HomePhone;
	}	
				
	// property: MobilePhone
	      								
	private String MobilePhone;
	public 	String getMobilePhone() {
		return this.MobilePhone;
	}
	public 	void setMobilePhone(String MobilePhone) {
		this.MobilePhone = MobilePhone;
	}	
				
	// property: SMSOptIn
	      								
	private String SMSOptIn;
	public 	String getSMSOptIn() {
		return this.SMSOptIn;
	}
	public 	void setSMSOptIn(String SMSOptIn) {
		this.SMSOptIn = SMSOptIn;
	}	
				
	// property: Gender
	      								
	private String Gender;
	public 	String getGender() {
		return this.Gender;
	}
	public 	void setGender(String Gender) {
		this.Gender = Gender;
	}	
				
	// property: LanguagePreference
	      								
	private String LanguagePreference;
	public 	String getLanguagePreference() {
		return this.LanguagePreference;
	}
	public 	void setLanguagePreference(String LanguagePreference) {
		this.LanguagePreference = LanguagePreference;
	}	
				
	// property: BaseBrand
	      								
	private String BaseBrand;
	public 	String getBaseBrand() {
		return this.BaseBrand;
	}
	public 	void setBaseBrand(String BaseBrand) {
		this.BaseBrand = BaseBrand;
	}	
				
}
