//------------------------------------------------------------------------------
// <autogenerated>
//     This code was generated by LoyaltyWare.
//
//     Changes to this file may cause incorrect behavior and will be lost if 
//     the code is regenerated.
// </autogenerated>
//------------------------------------------------------------------------------

package com.brierley.loyaltyware.clientlib.domainmodel.client;

import java.util.Date;

import com.brierley.loyaltyware.clientlib.annotations.*;
import com.brierley.loyaltyware.clientlib.domainmodel.framework.Member;
import com.brierley.loyaltyware.clientlib.domainmodel.framework.VirtualCard;

public class GetMemberRewardsIn {
	// property: MemberIdentity
	@LWIsRequired       								
	private String MemberIdentity;
	public 	String getMemberIdentity() {
		return this.MemberIdentity;
	}
	public 	void setMemberIdentity(String MemberIdentity) {
		this.MemberIdentity = MemberIdentity;
	}	
				
	// property: CategoryId
	      								
	private Long CategoryId;
	public 	Long getCategoryId() {
		return this.CategoryId;
	}
	public 	void setCategoryId(Long CategoryId) {
		this.CategoryId = CategoryId;
	}	
				
	// property: StartDate
	      								
	private Date StartDate;
	public 	Date getStartDate() {
		return this.StartDate;
	}
	public 	void setStartDate(Date StartDate) {
		this.StartDate = StartDate;
	}	
				
	// property: EndDate
	      								
	private Date EndDate;
	public 	Date getEndDate() {
		return this.EndDate;
	}
	public 	void setEndDate(Date EndDate) {
		this.EndDate = EndDate;
	}	
				
	// property: StartIndex
	      								
	private Integer StartIndex;
	public 	Integer getStartIndex() {
		return this.StartIndex;
	}
	public 	void setStartIndex(Integer StartIndex) {
		this.StartIndex = StartIndex;
	}	
				
	// property: BatchSize
	      								
	private Integer BatchSize;
	public 	Integer getBatchSize() {
		return this.BatchSize;
	}
	public 	void setBatchSize(Integer BatchSize) {
		this.BatchSize = BatchSize;
	}	
				
}
