//------------------------------------------------------------------------------
// <autogenerated>
//     This code was generated by LoyaltyWare.
//
//     Changes to this file may cause incorrect behavior and will be lost if 
//     the code is regenerated.
// </autogenerated>
//------------------------------------------------------------------------------

package com.brierley.loyaltyware.clientlib.domainmodel.client;

import java.util.Date;

import com.brierley.loyaltyware.clientlib.annotations.*;
import com.brierley.loyaltyware.clientlib.domainmodel.framework.Member;
import com.brierley.loyaltyware.clientlib.domainmodel.framework.VirtualCard;

public class GetRewardCatalogItemIn {
	// property: RewardID
	@LWIsRequired       								
	private Long RewardID;
	public 	Long getRewardID() {
		return this.RewardID;
	}
	public 	void setRewardID(Long RewardID) {
		this.RewardID = RewardID;
	}	
				
	// property: Language
	@LWStringLength(20)       								
	private String Language;
	public 	String getLanguage() {
		return this.Language;
	}
	public 	void setLanguage(String Language) {
		this.Language = Language;
	}	
				
	// property: ReturnAttributes
	      								
	private Boolean ReturnAttributes;
	public 	Boolean getReturnAttributes() {
		return this.ReturnAttributes;
	}
	public 	void setReturnAttributes(Boolean ReturnAttributes) {
		this.ReturnAttributes = ReturnAttributes;
	}	
				
}
