//------------------------------------------------------------------------------
// <autogenerated>
//     This code was generated by LoyaltyWare.
//
//     Changes to this file may cause incorrect behavior and will be lost if 
//     the code is regenerated.
// </autogenerated>
//------------------------------------------------------------------------------

package com.brierley.loyaltyware.clientlib.domainmodel.client;

import java.util.Date;

import com.brierley.loyaltyware.clientlib.annotations.*;
import com.brierley.loyaltyware.clientlib.domainmodel.framework.Member;
import com.brierley.loyaltyware.clientlib.domainmodel.framework.VirtualCard;

public class GetRewardCategoriesIn {
	// property: CategoryId
	      								
	private Long CategoryId;
	public 	Long getCategoryId() {
		return this.CategoryId;
	}
	public 	void setCategoryId(Long CategoryId) {
		this.CategoryId = CategoryId;
	}	
				
	// property: VisibleInLN
	      								
	private Boolean VisibleInLN;
	public 	Boolean getVisibleInLN() {
		return this.VisibleInLN;
	}
	public 	void setVisibleInLN(Boolean VisibleInLN) {
		this.VisibleInLN = VisibleInLN;
	}	
				
	// property: StartIndex
	      								
	private Integer StartIndex;
	public 	Integer getStartIndex() {
		return this.StartIndex;
	}
	public 	void setStartIndex(Integer StartIndex) {
		this.StartIndex = StartIndex;
	}	
				
	// property: BatchSize
	      								
	private Integer BatchSize;
	public 	Integer getBatchSize() {
		return this.BatchSize;
	}
	public 	void setBatchSize(Integer BatchSize) {
		this.BatchSize = BatchSize;
	}	
				
}
