//------------------------------------------------------------------------------
// <autogenerated>
//     This code was generated by LoyaltyWare.
//
//     Changes to this file may cause incorrect behavior and will be lost if 
//     the code is regenerated.
// </autogenerated>
//------------------------------------------------------------------------------

package com.brierley.loyaltyware.clientlib.domainmodel.client;

import java.util.Date;

import com.brierley.loyaltyware.clientlib.annotations.*;
import com.brierley.loyaltyware.clientlib.domainmodel.framework.Member;
import com.brierley.loyaltyware.clientlib.domainmodel.framework.VirtualCard;

public class GetSurveyIn {
	// property: Entity
	@LWIsRequired       								
	private Long Entity;
	public 	Long getEntity() {
		return this.Entity;
	}
	public 	void setEntity(Long Entity) {
		this.Entity = Entity;
	}	
				
	// property: SurveyName
	      								
	private String SurveyName;
	public 	String getSurveyName() {
		return this.SurveyName;
	}
	public 	void setSurveyName(String SurveyName) {
		this.SurveyName = SurveyName;
	}	
				
	// property: SurveyType
	@LWIsRequired       								
	private String SurveyType;
	public 	String getSurveyType() {
		return this.SurveyType;
	}
	public 	void setSurveyType(String SurveyType) {
		this.SurveyType = SurveyType;
	}	
				
	// property: IsComplete
	@LWIsRequired       								
	private Boolean IsComplete;
	public 	Boolean getIsComplete() {
		return this.IsComplete;
	}
	public 	void setIsComplete(Boolean IsComplete) {
		this.IsComplete = IsComplete;
	}	
				
}
