//------------------------------------------------------------------------------
// <autogenerated>
//     This code was generated by LoyaltyWare.
//
//     Changes to this file may cause incorrect behavior and will be lost if 
//     the code is regenerated.
// </autogenerated>
//------------------------------------------------------------------------------

package com.brierley.loyaltyware.clientlib.domainmodel.client;

import java.util.Date;
import com.brierley.loyaltyware.clientlib.annotations.*;
import com.brierley.loyaltyware.clientlib.domainmodel.LWClientDataObject;

public class HistoryTxnRewardRedeem extends LWClientDataObject {			    
	// property: TxnHeaderId
	@LWIsRequired @LWStringLength(50) 
	private String TxnHeaderId;
	public 	String getTxnHeaderId() {
		return this.TxnHeaderId;
	}
	public 	void setTxnHeaderId(String txnheaderid) {
		this.TxnHeaderId = txnheaderid;
	}

	// property: TxnDate
	@LWIsRequired 
	private Date TxnDate;
	public 	Date getTxnDate() {
		return this.TxnDate;
	}
	public 	void setTxnDate(Date txndate) {
		this.TxnDate = txndate;
	}

	// property: TxnDetailId
	@LWStringLength(50) 
	private String TxnDetailId;
	public 	String getTxnDetailId() {
		return this.TxnDetailId;
	}
	public 	void setTxnDetailId(String txndetailid) {
		this.TxnDetailId = txndetailid;
	}

	// property: ProgramId
	@LWIsRequired 
	private Integer ProgramId;
	public 	Integer getProgramId() {
		return this.ProgramId;
	}
	public 	void setProgramId(Integer programid) {
		this.ProgramId = programid;
	}

	// property: CertificateRedeemType
	@LWStringLength(3) 
	private String CertificateRedeemType;
	public 	String getCertificateRedeemType() {
		return this.CertificateRedeemType;
	}
	public 	void setCertificateRedeemType(String certificateredeemtype) {
		this.CertificateRedeemType = certificateredeemtype;
	}

	// property: CertificateCode
	@LWStringLength(50) 
	private String CertificateCode;
	public 	String getCertificateCode() {
		return this.CertificateCode;
	}
	public 	void setCertificateCode(String certificatecode) {
		this.CertificateCode = certificatecode;
	}

	// property: ProcessID
	
	private Long ProcessID;
	public 	Long getProcessID() {
		return this.ProcessID;
	}
	public 	void setProcessID(Long processid) {
		this.ProcessID = processid;
	}

	// property: CertificateDiscountAmount
	
	private java.math.BigDecimal CertificateDiscountAmount;
	public 	java.math.BigDecimal getCertificateDiscountAmount() {
		return this.CertificateDiscountAmount;
	}
	public 	void setCertificateDiscountAmount(java.math.BigDecimal certificatediscountamount) {
		this.CertificateDiscountAmount = certificatediscountamount;
	}

	// property: TxnRewardRedeemID
	
	private Long TxnRewardRedeemID;
	public 	Long getTxnRewardRedeemID() {
		return this.TxnRewardRedeemID;
	}
	public 	void setTxnRewardRedeemID(Long txnrewardredeemid) {
		this.TxnRewardRedeemID = txnrewardredeemid;
	}

	// property: ErrorMessage
	@LWStringLength(100) 
	private String ErrorMessage;
	public 	String getErrorMessage() {
		return this.ErrorMessage;
	}
	public 	void setErrorMessage(String errormessage) {
		this.ErrorMessage = errormessage;
	}

	// property: Vckey
	
	private Long Vckey;
	public 	Long getVckey() {
		return this.Vckey;
	}
	public 	void setVckey(Long vckey) {
		this.Vckey = vckey;
	}

	// property: FileId
	
	private Long FileId;
	public 	Long getFileId() {
		return this.FileId;
	}
	public 	void setFileId(Long fileid) {
		this.FileId = fileid;
	}

	// property: FileLineItem
	
	private Long FileLineItem;
	public 	Long getFileLineItem() {
		return this.FileLineItem;
	}
	public 	void setFileLineItem(Long filelineitem) {
		this.FileLineItem = filelineitem;
	}

}