//------------------------------------------------------------------------------
// <autogenerated>
//     This code was generated by LoyaltyWare.
//
//     Changes to this file may cause incorrect behavior and will be lost if 
//     the code is regenerated.
// </autogenerated>
//------------------------------------------------------------------------------

package com.brierley.loyaltyware.clientlib.domainmodel.client;

import java.util.Date;
import com.brierley.loyaltyware.clientlib.annotations.*;
import com.brierley.loyaltyware.clientlib.domainmodel.LWClientDataObject;

public class HistoryTxnTender extends LWClientDataObject {			    
	// property: TxnDate
	
	private Date TxnDate;
	public 	Date getTxnDate() {
		return this.TxnDate;
	}
	public 	void setTxnDate(Date txndate) {
		this.TxnDate = txndate;
	}

	// property: ProcessID
	
	private Long ProcessID;
	public 	Long getProcessID() {
		return this.ProcessID;
	}
	public 	void setProcessID(Long processid) {
		this.ProcessID = processid;
	}

	// property: StoreID
	@LWStringLength(50) 
	private String StoreID;
	public 	String getStoreID() {
		return this.StoreID;
	}
	public 	void setStoreID(String storeid) {
		this.StoreID = storeid;
	}

	// property: TxnHeaderID
	@LWIsRequired @LWStringLength(50) 
	private String TxnHeaderID;
	public 	String getTxnHeaderID() {
		return this.TxnHeaderID;
	}
	public 	void setTxnHeaderID(String txnheaderid) {
		this.TxnHeaderID = txnheaderid;
	}

	// property: TxnTenderID
	@LWIsRequired @LWStringLength(50) 
	private String TxnTenderID;
	public 	String getTxnTenderID() {
		return this.TxnTenderID;
	}
	public 	void setTxnTenderID(String txntenderid) {
		this.TxnTenderID = txntenderid;
	}

	// property: TenderType
	
	private Long TenderType;
	public 	Long getTenderType() {
		return this.TenderType;
	}
	public 	void setTenderType(Long tendertype) {
		this.TenderType = tendertype;
	}

	// property: TenderAmount
	@LWIsRequired 
	private java.math.BigDecimal TenderAmount;
	public 	java.math.BigDecimal getTenderAmount() {
		return this.TenderAmount;
	}
	public 	void setTenderAmount(java.math.BigDecimal tenderamount) {
		this.TenderAmount = tenderamount;
	}

	// property: TenderCurrency
	@LWStringLength(20) 
	private String TenderCurrency;
	public 	String getTenderCurrency() {
		return this.TenderCurrency;
	}
	public 	void setTenderCurrency(String tendercurrency) {
		this.TenderCurrency = tendercurrency;
	}

	// property: TenderTax
	
	private java.math.BigDecimal TenderTax;
	public 	java.math.BigDecimal getTenderTax() {
		return this.TenderTax;
	}
	public 	void setTenderTax(java.math.BigDecimal tendertax) {
		this.TenderTax = tendertax;
	}

	// property: TenderTaxRate
	
	private java.math.BigDecimal TenderTaxRate;
	public 	java.math.BigDecimal getTenderTaxRate() {
		return this.TenderTaxRate;
	}
	public 	void setTenderTaxRate(java.math.BigDecimal tendertaxrate) {
		this.TenderTaxRate = tendertaxrate;
	}

	// property: ErrorMessage
	@LWStringLength(100) 
	private String ErrorMessage;
	public 	String getErrorMessage() {
		return this.ErrorMessage;
	}
	public 	void setErrorMessage(String errormessage) {
		this.ErrorMessage = errormessage;
	}

	// property: Vckey
	
	private Long Vckey;
	public 	Long getVckey() {
		return this.Vckey;
	}
	public 	void setVckey(Long vckey) {
		this.Vckey = vckey;
	}

	// property: FileId
	
	private Long FileId;
	public 	Long getFileId() {
		return this.FileId;
	}
	public 	void setFileId(Long fileid) {
		this.FileId = fileid;
	}

	// property: FileLineItem
	
	private Long FileLineItem;
	public 	Long getFileLineItem() {
		return this.FileLineItem;
	}
	public 	void setFileLineItem(Long filelineitem) {
		this.FileLineItem = filelineitem;
	}

}