//------------------------------------------------------------------------------
// <autogenerated>
//     This code was generated by LoyaltyWare.
//
//     Changes to this file may cause incorrect behavior and will be lost if 
//     the code is regenerated.
// </autogenerated>
//------------------------------------------------------------------------------

package com.brierley.loyaltyware.clientlib.domainmodel.client;

import java.util.Date;

import com.brierley.loyaltyware.clientlib.annotations.*;
import com.brierley.loyaltyware.clientlib.domainmodel.framework.Member;
import com.brierley.loyaltyware.clientlib.domainmodel.framework.VirtualCard;

public class LoyaltyEventStruct {
	// property: Name
	@LWIsRequired @LWStringLength(150)       								
	private String Name;
	public 	String getName() {
		return this.Name;
	}
	public 	void setName(String Name) {
		this.Name = Name;
	}	
				
	// property: Description
	@LWStringLength(500)       								
	private String Description;
	public 	String getDescription() {
		return this.Description;
	}
	public 	void setDescription(String Description) {
		this.Description = Description;
	}	
				
	// property: DefaultPoints
	      								
	private java.math.BigDecimal DefaultPoints;
	public 	java.math.BigDecimal getDefaultPoints() {
		return this.DefaultPoints;
	}
	public 	void setDefaultPoints(java.math.BigDecimal DefaultPoints) {
		this.DefaultPoints = DefaultPoints;
	}	
				
}
