//------------------------------------------------------------------------------
// <autogenerated>
//     This code was generated by LoyaltyWare.
//
//     Changes to this file may cause incorrect behavior and will be lost if 
//     the code is regenerated.
// </autogenerated>
//------------------------------------------------------------------------------

package com.brierley.loyaltyware.clientlib.domainmodel.client;

import java.util.Date;
import com.brierley.loyaltyware.clientlib.annotations.*;
import com.brierley.loyaltyware.clientlib.domainmodel.LWClientDataObject;

public class MemberRewardFulfillment extends LWClientDataObject {			    
	// property: PointBalance
	
	private Long PointBalance;
	public 	Long getPointBalance() {
		return this.PointBalance;
	}
	public 	void setPointBalance(Long pointbalance) {
		this.PointBalance = pointbalance;
	}

	// property: RewardDescription
	@LWStringLength(50) 
	private String RewardDescription;
	public 	String getRewardDescription() {
		return this.RewardDescription;
	}
	public 	void setRewardDescription(String rewarddescription) {
		this.RewardDescription = rewarddescription;
	}

	// property: PointsRedeemed
	
	private Long PointsRedeemed;
	public 	Long getPointsRedeemed() {
		return this.PointsRedeemed;
	}
	public 	void setPointsRedeemed(Long pointsredeemed) {
		this.PointsRedeemed = pointsredeemed;
	}

	// property: EmployeeCode
	
	private Long EmployeeCode;
	public 	Long getEmployeeCode() {
		return this.EmployeeCode;
	}
	public 	void setEmployeeCode(Long employeecode) {
		this.EmployeeCode = employeecode;
	}

	// property: ExtendedPlayCode
	
	private Long ExtendedPlayCode;
	public 	Long getExtendedPlayCode() {
		return this.ExtendedPlayCode;
	}
	public 	void setExtendedPlayCode(Long extendedplaycode) {
		this.ExtendedPlayCode = extendedplaycode;
	}

	// property: MemberRewardID
	
	private Long MemberRewardID;
	public 	Long getMemberRewardID() {
		return this.MemberRewardID;
	}
	public 	void setMemberRewardID(Long memberrewardid) {
		this.MemberRewardID = memberrewardid;
	}

	// property: FirstName
	@LWStringLength(50) 
	private String FirstName;
	public 	String getFirstName() {
		return this.FirstName;
	}
	public 	void setFirstName(String firstname) {
		this.FirstName = firstname;
	}

	// property: LastName
	@LWStringLength(50) 
	private String LastName;
	public 	String getLastName() {
		return this.LastName;
	}
	public 	void setLastName(String lastname) {
		this.LastName = lastname;
	}

	// property: AddressLineOne
	@LWStringLength(100) 
	private String AddressLineOne;
	public 	String getAddressLineOne() {
		return this.AddressLineOne;
	}
	public 	void setAddressLineOne(String addresslineone) {
		this.AddressLineOne = addresslineone;
	}

	// property: AddressLineTwo
	@LWStringLength(100) 
	private String AddressLineTwo;
	public 	String getAddressLineTwo() {
		return this.AddressLineTwo;
	}
	public 	void setAddressLineTwo(String addresslinetwo) {
		this.AddressLineTwo = addresslinetwo;
	}

	// property: City
	@LWStringLength(50) 
	private String City;
	public 	String getCity() {
		return this.City;
	}
	public 	void setCity(String city) {
		this.City = city;
	}

	// property: StateOrProvince
	@LWStringLength(50) 
	private String StateOrProvince;
	public 	String getStateOrProvince() {
		return this.StateOrProvince;
	}
	public 	void setStateOrProvince(String stateorprovince) {
		this.StateOrProvince = stateorprovince;
	}

	// property: ZipOrPostalCode
	@LWStringLength(25) 
	private String ZipOrPostalCode;
	public 	String getZipOrPostalCode() {
		return this.ZipOrPostalCode;
	}
	public 	void setZipOrPostalCode(String ziporpostalcode) {
		this.ZipOrPostalCode = ziporpostalcode;
	}

	// property: Country
	@LWStringLength(50) 
	private String Country;
	public 	String getCountry() {
		return this.Country;
	}
	public 	void setCountry(String country) {
		this.Country = country;
	}

	// property: AddressMailable
	
	private Boolean AddressMailable;
	public 	Boolean getAddressMailable() {
		return this.AddressMailable;
	}
	public 	void setAddressMailable(Boolean addressmailable) {
		this.AddressMailable = addressmailable;
	}

	// property: DirectMailOptInDate
	
	private Date DirectMailOptInDate;
	public 	Date getDirectMailOptInDate() {
		return this.DirectMailOptInDate;
	}
	public 	void setDirectMailOptInDate(Date directmailoptindate) {
		this.DirectMailOptInDate = directmailoptindate;
	}

	// property: LanguagePreference
	@LWStringLength(20) 
	private String LanguagePreference;
	public 	String getLanguagePreference() {
		return this.LanguagePreference;
	}
	public 	void setLanguagePreference(String languagepreference) {
		this.LanguagePreference = languagepreference;
	}

	// property: RewardTier
	@LWStringLength(100) 
	private String RewardTier;
	public 	String getRewardTier() {
		return this.RewardTier;
	}
	public 	void setRewardTier(String rewardtier) {
		this.RewardTier = rewardtier;
	}

	// property: LoyaltyNumber
	@LWStringLength(20) 
	private String LoyaltyNumber;
	public 	String getLoyaltyNumber() {
		return this.LoyaltyNumber;
	}
	public 	void setLoyaltyNumber(String loyaltynumber) {
		this.LoyaltyNumber = loyaltynumber;
	}

	// property: HHKeyBarCode
	@LWStringLength(20) 
	private String HHKeyBarCode;
	public 	String getHHKeyBarCode() {
		return this.HHKeyBarCode;
	}
	public 	void setHHKeyBarCode(String hhkeybarcode) {
		this.HHKeyBarCode = hhkeybarcode;
	}

	// property: IsUnderAge
	
	private Boolean IsUnderAge;
	public 	Boolean getIsUnderAge() {
		return this.IsUnderAge;
	}
	public 	void setIsUnderAge(Boolean isunderage) {
		this.IsUnderAge = isunderage;
	}

	// property: StartingPoints
	
	private Long StartingPoints;
	public 	Long getStartingPoints() {
		return this.StartingPoints;
	}
	public 	void setStartingPoints(Long startingpoints) {
		this.StartingPoints = startingpoints;
	}

	// property: BasePointBalance
	
	private Long BasePointBalance;
	public 	Long getBasePointBalance() {
		return this.BasePointBalance;
	}
	public 	void setBasePointBalance(Long basepointbalance) {
		this.BasePointBalance = basepointbalance;
	}

	// property: BonusPointBalance
	
	private Long BonusPointBalance;
	public 	Long getBonusPointBalance() {
		return this.BonusPointBalance;
	}
	public 	void setBonusPointBalance(Long bonuspointbalance) {
		this.BonusPointBalance = bonuspointbalance;
	}

	// property: RewardPartNumber
	@LWStringLength(100) 
	private String RewardPartNumber;
	public 	String getRewardPartNumber() {
		return this.RewardPartNumber;
	}
	public 	void setRewardPartNumber(String rewardpartnumber) {
		this.RewardPartNumber = rewardpartnumber;
	}

	// property: BarCode
	@LWStringLength(50) 
	private String BarCode;
	public 	String getBarCode() {
		return this.BarCode;
	}
	public 	void setBarCode(String barcode) {
		this.BarCode = barcode;
	}

	// property: BaseLoyaltyBrand
	@LWStringLength(10) 
	private String BaseLoyaltyBrand;
	public 	String getBaseLoyaltyBrand() {
		return this.BaseLoyaltyBrand;
	}
	public 	void setBaseLoyaltyBrand(String baseloyaltybrand) {
		this.BaseLoyaltyBrand = baseloyaltybrand;
	}

	// property: PurchasedAEBrand
	
	private Long PurchasedAEBrand;
	public 	Long getPurchasedAEBrand() {
		return this.PurchasedAEBrand;
	}
	public 	void setPurchasedAEBrand(Long purchasedaebrand) {
		this.PurchasedAEBrand = purchasedaebrand;
	}

	// property: PurchasedAerieBrand
	
	private Long PurchasedAerieBrand;
	public 	Long getPurchasedAerieBrand() {
		return this.PurchasedAerieBrand;
	}
	public 	void setPurchasedAerieBrand(Long purchasedaeriebrand) {
		this.PurchasedAerieBrand = purchasedaeriebrand;
	}

	// property: PurchasedKidsBrand
	
	private Long PurchasedKidsBrand;
	public 	Long getPurchasedKidsBrand() {
		return this.PurchasedKidsBrand;
	}
	public 	void setPurchasedKidsBrand(Long purchasedkidsbrand) {
		this.PurchasedKidsBrand = purchasedkidsbrand;
	}

	// property: RewardType
	@LWStringLength(50) 
	private String RewardType;
	public 	String getRewardType() {
		return this.RewardType;
	}
	public 	void setRewardType(String rewardtype) {
		this.RewardType = rewardtype;
	}

	// property: ParentRewardId
	
	private Long ParentRewardId;
	public 	Long getParentRewardId() {
		return this.ParentRewardId;
	}
	public 	void setParentRewardId(Long parentrewardid) {
		this.ParentRewardId = parentrewardid;
	}

	// property: DirectMailOptIn
	
	private Boolean DirectMailOptIn;
	public 	Boolean getDirectMailOptIn() {
		return this.DirectMailOptIn;
	}
	public 	void setDirectMailOptIn(Boolean directmailoptin) {
		this.DirectMailOptIn = directmailoptin;
	}

}