//------------------------------------------------------------------------------
// <autogenerated>
//     This code was generated by LoyaltyWare.
//
//     Changes to this file may cause incorrect behavior and will be lost if 
//     the code is regenerated.
// </autogenerated>
//------------------------------------------------------------------------------

package com.brierley.loyaltyware.clientlib.domainmodel.client;

import java.util.Date;

import com.brierley.loyaltyware.clientlib.annotations.*;
import com.brierley.loyaltyware.clientlib.domainmodel.framework.Member;
import com.brierley.loyaltyware.clientlib.domainmodel.framework.VirtualCard;

public class MemberRewardInfoStruct {
	// property: MemberRewardID
	@LWIsRequired       								
	private Long MemberRewardID;
	public 	Long getMemberRewardID() {
		return this.MemberRewardID;
	}
	public 	void setMemberRewardID(Long MemberRewardID) {
		this.MemberRewardID = MemberRewardID;
	}	
				
	// property: RewardDefID
	@LWIsRequired       								
	private Long RewardDefID;
	public 	Long getRewardDefID() {
		return this.RewardDefID;
	}
	public 	void setRewardDefID(Long RewardDefID) {
		this.RewardDefID = RewardDefID;
	}	
				
	// property: FPOrderNumber
	      								
	private String FPOrderNumber;
	public 	String getFPOrderNumber() {
		return this.FPOrderNumber;
	}
	public 	void setFPOrderNumber(String FPOrderNumber) {
		this.FPOrderNumber = FPOrderNumber;
	}	
				
	// property: CertificateNumber
	      								
	private String CertificateNumber;
	public 	String getCertificateNumber() {
		return this.CertificateNumber;
	}
	public 	void setCertificateNumber(String CertificateNumber) {
		this.CertificateNumber = CertificateNumber;
	}	
				
	// property: AvailableBalance
	      								
	private java.math.BigDecimal AvailableBalance;
	public 	java.math.BigDecimal getAvailableBalance() {
		return this.AvailableBalance;
	}
	public 	void setAvailableBalance(java.math.BigDecimal AvailableBalance) {
		this.AvailableBalance = AvailableBalance;
	}	
				
	// property: DateIssued
	      								
	private Date DateIssued;
	public 	Date getDateIssued() {
		return this.DateIssued;
	}
	public 	void setDateIssued(Date DateIssued) {
		this.DateIssued = DateIssued;
	}	
				
	// property: ExpirationDate
	      								
	private Date ExpirationDate;
	public 	Date getExpirationDate() {
		return this.ExpirationDate;
	}
	public 	void setExpirationDate(Date ExpirationDate) {
		this.ExpirationDate = ExpirationDate;
	}	
				
	// property: FulfillmentDate
	      								
	private Date FulfillmentDate;
	public 	Date getFulfillmentDate() {
		return this.FulfillmentDate;
	}
	public 	void setFulfillmentDate(Date FulfillmentDate) {
		this.FulfillmentDate = FulfillmentDate;
	}	
				
	// property: RedemptionDate
	      								
	private Date RedemptionDate;
	public 	Date getRedemptionDate() {
		return this.RedemptionDate;
	}
	public 	void setRedemptionDate(Date RedemptionDate) {
		this.RedemptionDate = RedemptionDate;
	}	
				
	// property: OrderStatus
	      								
	private String OrderStatus;
	public 	String getOrderStatus() {
		return this.OrderStatus;
	}
	public 	void setOrderStatus(String OrderStatus) {
		this.OrderStatus = OrderStatus;
	}	
				
	// property: TrackingUrl
	      								
	private String TrackingUrl;
	public 	String getTrackingUrl() {
		return this.TrackingUrl;
	}
	public 	void setTrackingUrl(String TrackingUrl) {
		this.TrackingUrl = TrackingUrl;
	}	
				
	// property: TrackingNumber
	      								
	private String TrackingNumber;
	public 	String getTrackingNumber() {
		return this.TrackingNumber;
	}
	public 	void setTrackingNumber(String TrackingNumber) {
		this.TrackingNumber = TrackingNumber;
	}	
				
}
