//------------------------------------------------------------------------------
// <autogenerated>
//     This code was generated by LoyaltyWare.
//
//     Changes to this file may cause incorrect behavior and will be lost if 
//     the code is regenerated.
// </autogenerated>
//------------------------------------------------------------------------------

package com.brierley.loyaltyware.clientlib.domainmodel.client;

import java.util.Date;
import com.brierley.loyaltyware.clientlib.annotations.*;
import com.brierley.loyaltyware.clientlib.domainmodel.LWClientDataObject;

public class MemberBrand extends LWClientDataObject {			    
	// property: ChangedBy
	@LWStringLength(255) 
	private String ChangedBy;
	public 	String getChangedBy() {
		return this.ChangedBy;
	}
	public 	void setChangedBy(String changedby) {
		this.ChangedBy = changedby;
	}

	// property: BrandID
	
	private Long BrandID;
	public 	Long getBrandID() {
		return this.BrandID;
	}
	public 	void setBrandID(Long brandid) {
		this.BrandID = brandid;
	}

}