//------------------------------------------------------------------------------
// <autogenerated>
//     This code was generated by LoyaltyWare.
//
//     Changes to this file may cause incorrect behavior and will be lost if 
//     the code is regenerated.
// </autogenerated>
//------------------------------------------------------------------------------

package com.brierley.loyaltyware.clientlib.domainmodel.client;

import java.util.Date;
import com.brierley.loyaltyware.clientlib.annotations.*;
import com.brierley.loyaltyware.clientlib.domainmodel.LWClientDataObject;

public class MemberBraPromoCertRedeem extends LWClientDataObject {			    
	// property: RedemptionAmount
	
	private Long RedemptionAmount;
	public 	Long getRedemptionAmount() {
		return this.RedemptionAmount;
	}
	public 	void setRedemptionAmount(Long redemptionamount) {
		this.RedemptionAmount = redemptionamount;
	}

	// property: ReasonCode
	
	private Long ReasonCode;
	public 	Long getReasonCode() {
		return this.ReasonCode;
	}
	public 	void setReasonCode(Long reasoncode) {
		this.ReasonCode = reasoncode;
	}

	// property: RedemptionDate
	
	private Date RedemptionDate;
	public 	Date getRedemptionDate() {
		return this.RedemptionDate;
	}
	public 	void setRedemptionDate(Date redemptiondate) {
		this.RedemptionDate = redemptiondate;
	}

}