//------------------------------------------------------------------------------
// <autogenerated>
//     This code was generated by LoyaltyWare.
//
//     Changes to this file may cause incorrect behavior and will be lost if 
//     the code is regenerated.
// </autogenerated>
//------------------------------------------------------------------------------

package com.brierley.loyaltyware.clientlib.domainmodel.client;

import java.util.Date;
import com.brierley.loyaltyware.clientlib.annotations.*;
import com.brierley.loyaltyware.clientlib.domainmodel.LWClientDataObject;

public class MemberEngagements extends LWClientDataObject {			    
	// property: EngagementType
	@LWIsRequired @LWStringLength(255) 
	private String EngagementType;
	public 	String getEngagementType() {
		return this.EngagementType;
	}
	public 	void setEngagementType(String engagementtype) {
		this.EngagementType = engagementtype;
	}

	// property: Points
	@LWIsRequired 
	private Long Points;
	public 	Long getPoints() {
		return this.Points;
	}
	public 	void setPoints(Long points) {
		this.Points = points;
	}

	// property: VendorId
	@LWIsRequired @LWStringLength(255) 
	private String VendorId;
	public 	String getVendorId() {
		return this.VendorId;
	}
	public 	void setVendorId(String vendorid) {
		this.VendorId = vendorid;
	}

}