//------------------------------------------------------------------------------
// <autogenerated>
//     This code was generated by LoyaltyWare.
//
//     Changes to this file may cause incorrect behavior and will be lost if 
//     the code is regenerated.
// </autogenerated>
//------------------------------------------------------------------------------

package com.brierley.loyaltyware.clientlib.domainmodel.client;

import java.util.Date;
import com.brierley.loyaltyware.clientlib.annotations.*;
import com.brierley.loyaltyware.clientlib.domainmodel.LWClientDataObject;

public class MemberProactiveMerge extends LWClientDataObject {			    
	// property: AddressLineOne
	@LWStringLength(7) 
	private String AddressLineOne;
	public 	String getAddressLineOne() {
		return this.AddressLineOne;
	}
	public 	void setAddressLineOne(String addresslineone) {
		this.AddressLineOne = addresslineone;
	}

	// property: MemberCreateDate
	
	private Date MemberCreateDate;
	public 	Date getMemberCreateDate() {
		return this.MemberCreateDate;
	}
	public 	void setMemberCreateDate(Date membercreatedate) {
		this.MemberCreateDate = membercreatedate;
	}

	// property: MemberStatus
	
	private Long MemberStatus;
	public 	Long getMemberStatus() {
		return this.MemberStatus;
	}
	public 	void setMemberStatus(Long memberstatus) {
		this.MemberStatus = memberstatus;
	}

	// property: ChangedBy
	@LWStringLength(50) 
	private String ChangedBy;
	public 	String getChangedBy() {
		return this.ChangedBy;
	}
	public 	void setChangedBy(String changedby) {
		this.ChangedBy = changedby;
	}

	// property: FirstName
	@LWStringLength(4) 
	private String FirstName;
	public 	String getFirstName() {
		return this.FirstName;
	}
	public 	void setFirstName(String firstname) {
		this.FirstName = firstname;
	}

	// property: LastName
	@LWStringLength(50) 
	private String LastName;
	public 	String getLastName() {
		return this.LastName;
	}
	public 	void setLastName(String lastname) {
		this.LastName = lastname;
	}

	// property: ZipCode
	@LWStringLength(20) 
	private String ZipCode;
	public 	String getZipCode() {
		return this.ZipCode;
	}
	public 	void setZipCode(String zipcode) {
		this.ZipCode = zipcode;
	}

}