//------------------------------------------------------------------------------
// <autogenerated>
//     This code was generated by LoyaltyWare.
//
//     Changes to this file may cause incorrect behavior and will be lost if 
//     the code is regenerated.
// </autogenerated>
//------------------------------------------------------------------------------

package com.brierley.loyaltyware.clientlib.domainmodel.client;

import java.util.Date;
import com.brierley.loyaltyware.clientlib.annotations.*;
import com.brierley.loyaltyware.clientlib.domainmodel.LWClientDataObject;

public class MemberBraPromoCertSummary extends LWClientDataObject {			    
	// property: FulfillmentPeriod
	
	private Date FulfillmentPeriod;
	public 	Date getFulfillmentPeriod() {
		return this.FulfillmentPeriod;
	}
	public 	void setFulfillmentPeriod(Date fulfillmentperiod) {
		this.FulfillmentPeriod = fulfillmentperiod;
	}

	// property: ReasonCode
	
	private Long ReasonCode;
	public 	Long getReasonCode() {
		return this.ReasonCode;
	}
	public 	void setReasonCode(Long reasoncode) {
		this.ReasonCode = reasoncode;
	}

	// property: NumCertsAwarded
	
	private Long NumCertsAwarded;
	public 	Long getNumCertsAwarded() {
		return this.NumCertsAwarded;
	}
	public 	void setNumCertsAwarded(Long numcertsawarded) {
		this.NumCertsAwarded = numcertsawarded;
	}

	// property: NumberCertsRedeemed
	
	private Long NumberCertsRedeemed;
	public 	Long getNumberCertsRedeemed() {
		return this.NumberCertsRedeemed;
	}
	public 	void setNumberCertsRedeemed(Long numbercertsredeemed) {
		this.NumberCertsRedeemed = numbercertsredeemed;
	}

	// property: ProcessDate
	
	private Date ProcessDate;
	public 	Date getProcessDate() {
		return this.ProcessDate;
	}
	public 	void setProcessDate(Date processdate) {
		this.ProcessDate = processdate;
	}

	// property: InHomeDate
	
	private Date InHomeDate;
	public 	Date getInHomeDate() {
		return this.InHomeDate;
	}
	public 	void setInHomeDate(Date inhomedate) {
		this.InHomeDate = inhomedate;
	}

	// property: RedemptionDate
	
	private Date RedemptionDate;
	public 	Date getRedemptionDate() {
		return this.RedemptionDate;
	}
	public 	void setRedemptionDate(Date redemptiondate) {
		this.RedemptionDate = redemptiondate;
	}

}