//------------------------------------------------------------------------------
// <autogenerated>
//     This code was generated by LoyaltyWare.
//
//     Changes to this file may cause incorrect behavior and will be lost if 
//     the code is regenerated.
// </autogenerated>
//------------------------------------------------------------------------------

package com.brierley.loyaltyware.clientlib.domainmodel.client;

import java.util.Date;
import com.brierley.loyaltyware.clientlib.annotations.*;
import com.brierley.loyaltyware.clientlib.domainmodel.LWClientDataObject;

public class MemberBraPromoSummary extends LWClientDataObject {			    
	// property: BraFirstPurchaseDate
	
	private Date BraFirstPurchaseDate;
	public 	Date getBraFirstPurchaseDate() {
		return this.BraFirstPurchaseDate;
	}
	public 	void setBraFirstPurchaseDate(Date brafirstpurchasedate) {
		this.BraFirstPurchaseDate = brafirstpurchasedate;
	}

	// property: BraLifeTimeBalance
	
	private Integer BraLifeTimeBalance;
	public 	Integer getBraLifeTimeBalance() {
		return this.BraLifeTimeBalance;
	}
	public 	void setBraLifeTimeBalance(Integer bralifetimebalance) {
		this.BraLifeTimeBalance = bralifetimebalance;
	}

	// property: BraRollingBalance
	
	private Integer BraRollingBalance;
	public 	Integer getBraRollingBalance() {
		return this.BraRollingBalance;
	}
	public 	void setBraRollingBalance(Integer brarollingbalance) {
		this.BraRollingBalance = brarollingbalance;
	}

	// property: JeansFirstPurchaseDate
	
	private Date JeansFirstPurchaseDate;
	public 	Date getJeansFirstPurchaseDate() {
		return this.JeansFirstPurchaseDate;
	}
	public 	void setJeansFirstPurchaseDate(Date jeansfirstpurchasedate) {
		this.JeansFirstPurchaseDate = jeansfirstpurchasedate;
	}

	// property: JeansLifeTimeBalance
	
	private Integer JeansLifeTimeBalance;
	public 	Integer getJeansLifeTimeBalance() {
		return this.JeansLifeTimeBalance;
	}
	public 	void setJeansLifeTimeBalance(Integer jeanslifetimebalance) {
		this.JeansLifeTimeBalance = jeanslifetimebalance;
	}

	// property: JeansRollingBalance
	
	private Integer JeansRollingBalance;
	public 	Integer getJeansRollingBalance() {
		return this.JeansRollingBalance;
	}
	public 	void setJeansRollingBalance(Integer jeansrollingbalance) {
		this.JeansRollingBalance = jeansrollingbalance;
	}

	// property: CurrentBalance
	
	private Long CurrentBalance;
	public 	Long getCurrentBalance() {
		return this.CurrentBalance;
	}
	public 	void setCurrentBalance(Long currentbalance) {
		this.CurrentBalance = currentbalance;
	}

	// property: FulfillmentBalance
	
	private Long FulfillmentBalance;
	public 	Long getFulfillmentBalance() {
		return this.FulfillmentBalance;
	}
	public 	void setFulfillmentBalance(Long fulfillmentbalance) {
		this.FulfillmentBalance = fulfillmentbalance;
	}

	// property: TotalPurchased
	
	private Long TotalPurchased;
	public 	Long getTotalPurchased() {
		return this.TotalPurchased;
	}
	public 	void setTotalPurchased(Long totalpurchased) {
		this.TotalPurchased = totalpurchased;
	}

	// property: TotalReturned
	
	private Long TotalReturned;
	public 	Long getTotalReturned() {
		return this.TotalReturned;
	}
	public 	void setTotalReturned(Long totalreturned) {
		this.TotalReturned = totalreturned;
	}

}