//------------------------------------------------------------------------------
// <autogenerated>
//     This code was generated by LoyaltyWare.
//
//     Changes to this file may cause incorrect behavior and will be lost if 
//     the code is regenerated.
// </autogenerated>
//------------------------------------------------------------------------------

package com.brierley.loyaltyware.clientlib.domainmodel.client;

import java.util.Date;
import com.brierley.loyaltyware.clientlib.annotations.*;
import com.brierley.loyaltyware.clientlib.domainmodel.LWClientDataObject;

public class MemberPromoQueue extends LWClientDataObject {			    
	// property: Source
	@LWStringLength(50) 
	private String Source;
	public 	String getSource() {
		return this.Source;
	}
	public 	void setSource(String source) {
		this.Source = source;
	}

	// property: TxnDate
	
	private Date TxnDate;
	public 	Date getTxnDate() {
		return this.TxnDate;
	}
	public 	void setTxnDate(Date txndate) {
		this.TxnDate = txndate;
	}

	// property: TxnNumber
	@LWStringLength(25) 
	private String TxnNumber;
	public 	String getTxnNumber() {
		return this.TxnNumber;
	}
	public 	void setTxnNumber(String txnnumber) {
		this.TxnNumber = txnnumber;
	}

	// property: StoreNumber
	
	private Long StoreNumber;
	public 	Long getStoreNumber() {
		return this.StoreNumber;
	}
	public 	void setStoreNumber(Long storenumber) {
		this.StoreNumber = storenumber;
	}

	// property: TxnRegisterNumber
	@LWStringLength(15) 
	private String TxnRegisterNumber;
	public 	String getTxnRegisterNumber() {
		return this.TxnRegisterNumber;
	}
	public 	void setTxnRegisterNumber(String txnregisternumber) {
		this.TxnRegisterNumber = txnregisternumber;
	}

	// property: PromoType
	
	private Integer PromoType;
	public 	Integer getPromoType() {
		return this.PromoType;
	}
	public 	void setPromoType(Integer promotype) {
		this.PromoType = promotype;
	}

}