//------------------------------------------------------------------------------
// <autogenerated>
//     This code was generated by LoyaltyWare.
//
//     Changes to this file may cause incorrect behavior and will be lost if 
//     the code is regenerated.
// </autogenerated>
//------------------------------------------------------------------------------

package com.brierley.loyaltyware.clientlib.domainmodel.client;

import java.util.Date;
import com.brierley.loyaltyware.clientlib.annotations.*;
import com.brierley.loyaltyware.clientlib.domainmodel.LWClientDataObject;

public class MobileAlerts extends LWClientDataObject {			    
	// property: LoyaltyIdNumber
	
	private Long LoyaltyIdNumber;
	public 	Long getLoyaltyIdNumber() {
		return this.LoyaltyIdNumber;
	}
	public 	void setLoyaltyIdNumber(Long loyaltyidnumber) {
		this.LoyaltyIdNumber = loyaltyidnumber;
	}

}