//------------------------------------------------------------------------------
// <autogenerated>
//     This code was generated by LoyaltyWare.
//
//     Changes to this file may cause incorrect behavior and will be lost if 
//     the code is regenerated.
// </autogenerated>
//------------------------------------------------------------------------------

package com.brierley.loyaltyware.clientlib.domainmodel.client;

import java.util.Date;

import com.brierley.loyaltyware.clientlib.annotations.*;
import com.brierley.loyaltyware.clientlib.domainmodel.framework.Member;
import com.brierley.loyaltyware.clientlib.domainmodel.framework.VirtualCard;

public class OtherPointsHistoryStruct {
	// property: CurrencyAmount
	@LWIsRequired       								
	private java.math.BigDecimal CurrencyAmount;
	public 	java.math.BigDecimal getCurrencyAmount() {
		return this.CurrencyAmount;
	}
	public 	void setCurrencyAmount(java.math.BigDecimal CurrencyAmount) {
		this.CurrencyAmount = CurrencyAmount;
	}	
				
	// property: PointTxnType
	@LWIsRequired       								
	private String PointTxnType;
	public 	String getPointTxnType() {
		return this.PointTxnType;
	}
	public 	void setPointTxnType(String PointTxnType) {
		this.PointTxnType = PointTxnType;
	}	
				
	// property: LoyaltyEvent
	@LWIsRequired       								
	private String LoyaltyEvent;
	public 	String getLoyaltyEvent() {
		return this.LoyaltyEvent;
	}
	public 	void setLoyaltyEvent(String LoyaltyEvent) {
		this.LoyaltyEvent = LoyaltyEvent;
	}	
				
	// property: LoyaltyCurrency
	@LWIsRequired       								
	private String LoyaltyCurrency;
	public 	String getLoyaltyCurrency() {
		return this.LoyaltyCurrency;
	}
	public 	void setLoyaltyCurrency(String LoyaltyCurrency) {
		this.LoyaltyCurrency = LoyaltyCurrency;
	}	
				
	// property: TxnDate
	@LWIsRequired       								
	private Date TxnDate;
	public 	Date getTxnDate() {
		return this.TxnDate;
	}
	public 	void setTxnDate(Date TxnDate) {
		this.TxnDate = TxnDate;
	}	
				
	// property: OwnerType
	      								
	private String OwnerType;
	public 	String getOwnerType() {
		return this.OwnerType;
	}
	public 	void setOwnerType(String OwnerType) {
		this.OwnerType = OwnerType;
	}	
				
	// property: OwnerId
	      								
	private Long OwnerId;
	public 	Long getOwnerId() {
		return this.OwnerId;
	}
	public 	void setOwnerId(Long OwnerId) {
		this.OwnerId = OwnerId;
	}	
				
	// property: RowKey
	      								
	private Long RowKey;
	public 	Long getRowKey() {
		return this.RowKey;
	}
	public 	void setRowKey(Long RowKey) {
		this.RowKey = RowKey;
	}	
				
	// property: PromoCode
	      								
	private String PromoCode;
	public 	String getPromoCode() {
		return this.PromoCode;
	}
	public 	void setPromoCode(String PromoCode) {
		this.PromoCode = PromoCode;
	}	
				
	// property: ExpirationDate
	      								
	private Date ExpirationDate;
	public 	Date getExpirationDate() {
		return this.ExpirationDate;
	}
	public 	void setExpirationDate(Date ExpirationDate) {
		this.ExpirationDate = ExpirationDate;
	}	
				
	// property: Notes
	@LWStringLength(500)       								
	private String Notes;
	public 	String getNotes() {
		return this.Notes;
	}
	public 	void setNotes(String Notes) {
		this.Notes = Notes;
	}	
				
}
