//------------------------------------------------------------------------------
// <autogenerated>
//     This code was generated by LoyaltyWare.
//
//     Changes to this file may cause incorrect behavior and will be lost if 
//     the code is regenerated.
// </autogenerated>
//------------------------------------------------------------------------------

package com.brierley.loyaltyware.clientlib.domainmodel.client;

import java.util.Date;

import com.brierley.loyaltyware.clientlib.annotations.*;
import com.brierley.loyaltyware.clientlib.domainmodel.framework.Member;
import com.brierley.loyaltyware.clientlib.domainmodel.framework.VirtualCard;

public class RedeemMemberRewardIn {
	// property: MemberRewardID
	@LWIsRequired       								
	private Long MemberRewardID;
	public 	Long getMemberRewardID() {
		return this.MemberRewardID;
	}
	public 	void setMemberRewardID(Long MemberRewardID) {
		this.MemberRewardID = MemberRewardID;
	}	
				
	// property: AvailableBalance
	      								
	private java.math.BigDecimal AvailableBalance;
	public 	java.math.BigDecimal getAvailableBalance() {
		return this.AvailableBalance;
	}
	public 	void setAvailableBalance(java.math.BigDecimal AvailableBalance) {
		this.AvailableBalance = AvailableBalance;
	}	
				
	// property: ExpirationDate
	      								
	private Date ExpirationDate;
	public 	Date getExpirationDate() {
		return this.ExpirationDate;
	}
	public 	void setExpirationDate(Date ExpirationDate) {
		this.ExpirationDate = ExpirationDate;
	}	
				
	// property: RedemptionDate
	      								
	private Date RedemptionDate;
	public 	Date getRedemptionDate() {
		return this.RedemptionDate;
	}
	public 	void setRedemptionDate(Date RedemptionDate) {
		this.RedemptionDate = RedemptionDate;
	}	
				
}
