//------------------------------------------------------------------------------
// <autogenerated>
//     This code was generated by LoyaltyWare.
//
//     Changes to this file may cause incorrect behavior and will be lost if 
//     the code is regenerated.
// </autogenerated>
//------------------------------------------------------------------------------

package com.brierley.loyaltyware.clientlib.domainmodel.client;

import java.util.Date;
import com.brierley.loyaltyware.clientlib.annotations.*;
import com.brierley.loyaltyware.clientlib.domainmodel.LWClientDataObject;

public class RefCardType extends LWClientDataObject {			    
	// property: ClientCardType
	@LWStringLength(2) 
	private String ClientCardType;
	public 	String getClientCardType() {
		return this.ClientCardType;
	}
	public 	void setClientCardType(String clientcardtype) {
		this.ClientCardType = clientcardtype;
	}

	// property: CardTypeCode
	
	private Long CardTypeCode;
	public 	Long getCardTypeCode() {
		return this.CardTypeCode;
	}
	public 	void setCardTypeCode(Long cardtypecode) {
		this.CardTypeCode = cardtypecode;
	}

	// property: Description
	@LWStringLength(255) 
	private String Description;
	public 	String getDescription() {
		return this.Description;
	}
	public 	void setDescription(String description) {
		this.Description = description;
	}

}