//------------------------------------------------------------------------------
// <autogenerated>
//     This code was generated by LoyaltyWare.
//
//     Changes to this file may cause incorrect behavior and will be lost if 
//     the code is regenerated.
// </autogenerated>
//------------------------------------------------------------------------------

package com.brierley.loyaltyware.clientlib.domainmodel.client;

import java.util.Date;
import com.brierley.loyaltyware.clientlib.annotations.*;
import com.brierley.loyaltyware.clientlib.domainmodel.LWClientDataObject;

public class RefGender extends LWClientDataObject {			    
	// property: GenderCode
	
	private Long GenderCode;
	public 	Long getGenderCode() {
		return this.GenderCode;
	}
	public 	void setGenderCode(Long gendercode) {
		this.GenderCode = gendercode;
	}

	// property: Description
	@LWStringLength(255) 
	private String Description;
	public 	String getDescription() {
		return this.Description;
	}
	public 	void setDescription(String description) {
		this.Description = description;
	}

}