//------------------------------------------------------------------------------
// <autogenerated>
//     This code was generated by LoyaltyWare.
//
//     Changes to this file may cause incorrect behavior and will be lost if 
//     the code is regenerated.
// </autogenerated>
//------------------------------------------------------------------------------

package com.brierley.loyaltyware.clientlib.domainmodel.client;

import java.util.Date;

import com.brierley.loyaltyware.clientlib.annotations.*;
import com.brierley.loyaltyware.clientlib.domainmodel.framework.Member;
import com.brierley.loyaltyware.clientlib.domainmodel.framework.VirtualCard;

public class RewardCatalogSummaryStruct {
	// property: RewardID
	@LWIsRequired       								
	private Long RewardID;
	public 	Long getRewardID() {
		return this.RewardID;
	}
	public 	void setRewardID(Long RewardID) {
		this.RewardID = RewardID;
	}	
				
	// property: RewardName
	@LWIsRequired       								
	private String RewardName;
	public 	String getRewardName() {
		return this.RewardName;
	}
	public 	void setRewardName(String RewardName) {
		this.RewardName = RewardName;
	}	
				
	// property: TypeCode
	      								
	private String TypeCode;
	public 	String getTypeCode() {
		return this.TypeCode;
	}
	public 	void setTypeCode(String TypeCode) {
		this.TypeCode = TypeCode;
	}	
				
	// property: CategoryId
	      								
	private Long CategoryId;
	public 	Long getCategoryId() {
		return this.CategoryId;
	}
	public 	void setCategoryId(Long CategoryId) {
		this.CategoryId = CategoryId;
	}	
				
	// property: ShortDescription
	      								
	private String ShortDescription;
	public 	String getShortDescription() {
		return this.ShortDescription;
	}
	public 	void setShortDescription(String ShortDescription) {
		this.ShortDescription = ShortDescription;
	}	
				
	// property: CatalogStartDate
	      								
	private Date CatalogStartDate;
	public 	Date getCatalogStartDate() {
		return this.CatalogStartDate;
	}
	public 	void setCatalogStartDate(Date CatalogStartDate) {
		this.CatalogStartDate = CatalogStartDate;
	}	
				
	// property: CatalogEndDate
	      								
	private Date CatalogEndDate;
	public 	Date getCatalogEndDate() {
		return this.CatalogEndDate;
	}
	public 	void setCatalogEndDate(Date CatalogEndDate) {
		this.CatalogEndDate = CatalogEndDate;
	}	
				
	// property: CurrencyToEarn
	      								
	private java.math.BigDecimal CurrencyToEarn;
	public 	java.math.BigDecimal getCurrencyToEarn() {
		return this.CurrencyToEarn;
	}
	public 	void setCurrencyToEarn(java.math.BigDecimal CurrencyToEarn) {
		this.CurrencyToEarn = CurrencyToEarn;
	}	
				
	// property: SmallImageFile
	      								
	private String SmallImageFile;
	public 	String getSmallImageFile() {
		return this.SmallImageFile;
	}
	public 	void setSmallImageFile(String SmallImageFile) {
		this.SmallImageFile = SmallImageFile;
	}	
				
}
