//------------------------------------------------------------------------------
// <autogenerated>
//     This code was generated by LoyaltyWare.
//
//     Changes to this file may cause incorrect behavior and will be lost if 
//     the code is regenerated.
// </autogenerated>
//------------------------------------------------------------------------------

package com.brierley.loyaltyware.clientlib.domainmodel.client;

import java.util.Date;
import com.brierley.loyaltyware.clientlib.annotations.*;
import com.brierley.loyaltyware.clientlib.domainmodel.LWClientDataObject;

public class RewardBarCodes extends LWClientDataObject {			    
	// property: EffectiveStartDate
	
	private Date EffectiveStartDate;
	public 	Date getEffectiveStartDate() {
		return this.EffectiveStartDate;
	}
	public 	void setEffectiveStartDate(Date effectivestartdate) {
		this.EffectiveStartDate = effectivestartdate;
	}

	// property: TypeCode
	@LWIsRequired @LWStringLength(25) 
	private String TypeCode;
	public 	String getTypeCode() {
		return this.TypeCode;
	}
	public 	void setTypeCode(String typecode) {
		this.TypeCode = typecode;
	}

	// property: BarCode
	@LWIsRequired @LWStringLength(50) 
	private String BarCode;
	public 	String getBarCode() {
		return this.BarCode;
	}
	public 	void setBarCode(String barcode) {
		this.BarCode = barcode;
	}

	// property: Status
	@LWIsRequired 
	private Integer Status;
	public 	Integer getStatus() {
		return this.Status;
	}
	public 	void setStatus(Integer status) {
		this.Status = status;
	}

	// property: EffectiveEndDate
	
	private Date EffectiveEndDate;
	public 	Date getEffectiveEndDate() {
		return this.EffectiveEndDate;
	}
	public 	void setEffectiveEndDate(Date effectiveenddate) {
		this.EffectiveEndDate = effectiveenddate;
	}

}