//------------------------------------------------------------------------------
// <autogenerated>
//     This code was generated by LoyaltyWare.
//
//     Changes to this file may cause incorrect behavior and will be lost if 
//     the code is regenerated.
// </autogenerated>
//------------------------------------------------------------------------------

package com.brierley.loyaltyware.clientlib.domainmodel.client;

import java.util.Date;

import com.brierley.loyaltyware.clientlib.annotations.*;
import com.brierley.loyaltyware.clientlib.domainmodel.framework.Member;
import com.brierley.loyaltyware.clientlib.domainmodel.framework.VirtualCard;

public class ShippingAddressStruct {
	// property: AddressLineOne
	      								
	private String AddressLineOne;
	public 	String getAddressLineOne() {
		return this.AddressLineOne;
	}
	public 	void setAddressLineOne(String AddressLineOne) {
		this.AddressLineOne = AddressLineOne;
	}	
				
	// property: AddressLineTwo
	      								
	private String AddressLineTwo;
	public 	String getAddressLineTwo() {
		return this.AddressLineTwo;
	}
	public 	void setAddressLineTwo(String AddressLineTwo) {
		this.AddressLineTwo = AddressLineTwo;
	}	
				
	// property: AddressLineThree
	      								
	private String AddressLineThree;
	public 	String getAddressLineThree() {
		return this.AddressLineThree;
	}
	public 	void setAddressLineThree(String AddressLineThree) {
		this.AddressLineThree = AddressLineThree;
	}	
				
	// property: AddressLineFour
	      								
	private String AddressLineFour;
	public 	String getAddressLineFour() {
		return this.AddressLineFour;
	}
	public 	void setAddressLineFour(String AddressLineFour) {
		this.AddressLineFour = AddressLineFour;
	}	
				
	// property: City
	      								
	private String City;
	public 	String getCity() {
		return this.City;
	}
	public 	void setCity(String City) {
		this.City = City;
	}	
				
	// property: StateOrProvince
	      								
	private String StateOrProvince;
	public 	String getStateOrProvince() {
		return this.StateOrProvince;
	}
	public 	void setStateOrProvince(String StateOrProvince) {
		this.StateOrProvince = StateOrProvince;
	}	
				
	// property: ZipOrPostalCode
	      								
	private String ZipOrPostalCode;
	public 	String getZipOrPostalCode() {
		return this.ZipOrPostalCode;
	}
	public 	void setZipOrPostalCode(String ZipOrPostalCode) {
		this.ZipOrPostalCode = ZipOrPostalCode;
	}	
				
	// property: County
	      								
	private String County;
	public 	String getCounty() {
		return this.County;
	}
	public 	void setCounty(String County) {
		this.County = County;
	}	
				
	// property: Country
	      								
	private String Country;
	public 	String getCountry() {
		return this.Country;
	}
	public 	void setCountry(String Country) {
		this.Country = Country;
	}	
				
}
