//------------------------------------------------------------------------------
// <autogenerated>
//     This code was generated by LoyaltyWare.
//
//     Changes to this file may cause incorrect behavior and will be lost if 
//     the code is regenerated.
// </autogenerated>
//------------------------------------------------------------------------------

package com.brierley.loyaltyware.clientlib.domainmodel.client;

import java.util.Date;
import com.brierley.loyaltyware.clientlib.annotations.*;
import com.brierley.loyaltyware.clientlib.domainmodel.LWClientDataObject;

public class SocialMediaPost extends LWClientDataObject {			    
	// property: CommentCount
	
	private Integer CommentCount;
	public 	Integer getCommentCount() {
		return this.CommentCount;
	}
	public 	void setCommentCount(Integer commentcount) {
		this.CommentCount = commentcount;
	}

	// property: Following
	
	private Integer Following;
	public 	Integer getFollowing() {
		return this.Following;
	}
	public 	void setFollowing(Integer following) {
		this.Following = following;
	}

	// property: Followers
	
	private Integer Followers;
	public 	Integer getFollowers() {
		return this.Followers;
	}
	public 	void setFollowers(Integer followers) {
		this.Followers = followers;
	}

	// property: PublishDate
	
	private Date PublishDate;
	public 	Date getPublishDate() {
		return this.PublishDate;
	}
	public 	void setPublishDate(Date publishdate) {
		this.PublishDate = publishdate;
	}

	// property: ViewCount
	
	private Integer ViewCount;
	public 	Integer getViewCount() {
		return this.ViewCount;
	}
	public 	void setViewCount(Integer viewcount) {
		this.ViewCount = viewcount;
	}

	// property: Content
	@LWStringLength(500) 
	private String Content;
	public 	String getContent() {
		return this.Content;
	}
	public 	void setContent(String content) {
		this.Content = content;
	}

	// property: ArticleID
	@LWStringLength(25) 
	private String ArticleID;
	public 	String getArticleID() {
		return this.ArticleID;
	}
	public 	void setArticleID(String articleid) {
		this.ArticleID = articleid;
	}

	// property: Headline
	@LWStringLength(500) 
	private String Headline;
	public 	String getHeadline() {
		return this.Headline;
	}
	public 	void setHeadline(String headline) {
		this.Headline = headline;
	}

	// property: ArticleURL
	@LWStringLength(255) 
	private String ArticleURL;
	public 	String getArticleURL() {
		return this.ArticleURL;
	}
	public 	void setArticleURL(String articleurl) {
		this.ArticleURL = articleurl;
	}

	// property: MediaProvider
	@LWStringLength(255) 
	private String MediaProvider;
	public 	String getMediaProvider() {
		return this.MediaProvider;
	}
	public 	void setMediaProvider(String mediaprovider) {
		this.MediaProvider = mediaprovider;
	}

}