//------------------------------------------------------------------------------
// <autogenerated>
//     This code was generated by LoyaltyWare.
//
//     Changes to this file may cause incorrect behavior and will be lost if 
//     the code is regenerated.
// </autogenerated>
//------------------------------------------------------------------------------

package com.brierley.loyaltyware.clientlib.domainmodel.client;

import java.util.Date;

import com.brierley.loyaltyware.clientlib.annotations.*;
import com.brierley.loyaltyware.clientlib.domainmodel.framework.Member;
import com.brierley.loyaltyware.clientlib.domainmodel.framework.VirtualCard;

public class TerminateMemberIn {
	// property: MemberIdentity
	@LWIsRequired       								
	private String MemberIdentity;
	public 	String getMemberIdentity() {
		return this.MemberIdentity;
	}
	public 	void setMemberIdentity(String MemberIdentity) {
		this.MemberIdentity = MemberIdentity;
	}	
				
	// property: EffectiveDate
	      								
	private Date EffectiveDate;
	public 	Date getEffectiveDate() {
		return this.EffectiveDate;
	}
	public 	void setEffectiveDate(Date EffectiveDate) {
		this.EffectiveDate = EffectiveDate;
	}	
				
	// property: UpdateMemberStatusReason
	@LWIsRequired @LWStringLength(255)       								
	private String UpdateMemberStatusReason;
	public 	String getUpdateMemberStatusReason() {
		return this.UpdateMemberStatusReason;
	}
	public 	void setUpdateMemberStatusReason(String UpdateMemberStatusReason) {
		this.UpdateMemberStatusReason = UpdateMemberStatusReason;
	}	
				
}
