//------------------------------------------------------------------------------
// <autogenerated>
//     This code was generated by LoyaltyWare.
//
//     Changes to this file may cause incorrect behavior and will be lost if 
//     the code is regenerated.
// </autogenerated>
//------------------------------------------------------------------------------

package com.brierley.loyaltyware.clientlib.domainmodel.client;

import java.util.Date;
import com.brierley.loyaltyware.clientlib.annotations.*;
import com.brierley.loyaltyware.clientlib.domainmodel.LWClientDataObject;

public class TlogAudit extends LWClientDataObject {			    
	// property: AEStoreNumber
	
	private Integer AEStoreNumber;
	public 	Integer getAEStoreNumber() {
		return this.AEStoreNumber;
	}
	public 	void setAEStoreNumber(Integer aestorenumber) {
		this.AEStoreNumber = aestorenumber;
	}

	// property: AETransactionCount
	
	private Integer AETransactionCount;
	public 	Integer getAETransactionCount() {
		return this.AETransactionCount;
	}
	public 	void setAETransactionCount(Integer aetransactioncount) {
		this.AETransactionCount = aetransactioncount;
	}

	// property: AELoyaltyCount
	
	private Integer AELoyaltyCount;
	public 	Integer getAELoyaltyCount() {
		return this.AELoyaltyCount;
	}
	public 	void setAELoyaltyCount(Integer aeloyaltycount) {
		this.AELoyaltyCount = aeloyaltycount;
	}

	// property: BPStoreNumber
	
	private Integer BPStoreNumber;
	public 	Integer getBPStoreNumber() {
		return this.BPStoreNumber;
	}
	public 	void setBPStoreNumber(Integer bpstorenumber) {
		this.BPStoreNumber = bpstorenumber;
	}

	// property: BPTransactionCount
	
	private Integer BPTransactionCount;
	public 	Integer getBPTransactionCount() {
		return this.BPTransactionCount;
	}
	public 	void setBPTransactionCount(Integer bptransactioncount) {
		this.BPTransactionCount = bptransactioncount;
	}

	// property: BPLoyaltyCount
	
	private Integer BPLoyaltyCount;
	public 	Integer getBPLoyaltyCount() {
		return this.BPLoyaltyCount;
	}
	public 	void setBPLoyaltyCount(Integer bployaltycount) {
		this.BPLoyaltyCount = bployaltycount;
	}

}