//------------------------------------------------------------------------------
// <autogenerated>
//     This code was generated by LoyaltyWare.
//
//     Changes to this file may cause incorrect behavior and will be lost if 
//     the code is regenerated.
// </autogenerated>
//------------------------------------------------------------------------------

package com.brierley.loyaltyware.clientlib.domainmodel.client;

import java.util.Date;

import com.brierley.loyaltyware.clientlib.annotations.*;
import com.brierley.loyaltyware.clientlib.domainmodel.framework.Member;
import com.brierley.loyaltyware.clientlib.domainmodel.framework.VirtualCard;

public class TransactionHeadersStruct {
	// property: TransactionNumber
	@LWIsRequired       								
	private String TransactionNumber;
	public 	String getTransactionNumber() {
		return this.TransactionNumber;
	}
	public 	void setTransactionNumber(String TransactionNumber) {
		this.TransactionNumber = TransactionNumber;
	}	
				
	// property: StoreName
	@LWIsRequired       								
	private String StoreName;
	public 	String getStoreName() {
		return this.StoreName;
	}
	public 	void setStoreName(String StoreName) {
		this.StoreName = StoreName;
	}	
				
	// property: PurchaseDate
	      								
	private String PurchaseDate;
	public 	String getPurchaseDate() {
		return this.PurchaseDate;
	}
	public 	void setPurchaseDate(String PurchaseDate) {
		this.PurchaseDate = PurchaseDate;
	}	
				
	// property: Description
	@LWIsRequired       								
	private String Description;
	public 	String getDescription() {
		return this.Description;
	}
	public 	void setDescription(String Description) {
		this.Description = Description;
	}	
				
	// property: Points
	@LWIsRequired       								
	private String Points;
	public 	String getPoints() {
		return this.Points;
	}
	public 	void setPoints(String Points) {
		this.Points = Points;
	}	
				
}
