//------------------------------------------------------------------------------
// <autogenerated>
//     This code was generated by LoyaltyWare.
//
//     Changes to this file may cause incorrect behavior and will be lost if 
//     the code is regenerated.
// </autogenerated>
//------------------------------------------------------------------------------

package com.brierley.loyaltyware.clientlib.domainmodel.client;

import java.util.Date;
import com.brierley.loyaltyware.clientlib.annotations.*;
import com.brierley.loyaltyware.clientlib.domainmodel.LWClientDataObject;

public class TxnDetailItem extends LWClientDataObject {			    
	// property: DtlClassCode
	@LWStringLength(50) 
	private String DtlClassCode;
	public 	String getDtlClassCode() {
		return this.DtlClassCode;
	}
	public 	void setDtlClassCode(String dtlclasscode) {
		this.DtlClassCode = dtlclasscode;
	}

	// property: ReasonCode
	@LWStringLength(10) 
	private String ReasonCode;
	public 	String getReasonCode() {
		return this.ReasonCode;
	}
	public 	void setReasonCode(String reasoncode) {
		this.ReasonCode = reasoncode;
	}

	// property: TxnHeaderId
	@LWStringLength(50) 
	private String TxnHeaderId;
	public 	String getTxnHeaderId() {
		return this.TxnHeaderId;
	}
	public 	void setTxnHeaderId(String txnheaderid) {
		this.TxnHeaderId = txnheaderid;
	}

	// property: TxnDate
	
	private Date TxnDate;
	public 	Date getTxnDate() {
		return this.TxnDate;
	}
	public 	void setTxnDate(Date txndate) {
		this.TxnDate = txndate;
	}

	// property: TxnStoreId
	
	private Long TxnStoreId;
	public 	Long getTxnStoreId() {
		return this.TxnStoreId;
	}
	public 	void setTxnStoreId(Long txnstoreid) {
		this.TxnStoreId = txnstoreid;
	}

	// property: TxnDetailId
	@LWIsRequired @LWStringLength(50) 
	private String TxnDetailId;
	public 	String getTxnDetailId() {
		return this.TxnDetailId;
	}
	public 	void setTxnDetailId(String txndetailid) {
		this.TxnDetailId = txndetailid;
	}

	// property: DtlItemLineNbr
	
	private Integer DtlItemLineNbr;
	public 	Integer getDtlItemLineNbr() {
		return this.DtlItemLineNbr;
	}
	public 	void setDtlItemLineNbr(Integer dtlitemlinenbr) {
		this.DtlItemLineNbr = dtlitemlinenbr;
	}

	// property: DtlProductId
	
	private Integer DtlProductId;
	public 	Integer getDtlProductId() {
		return this.DtlProductId;
	}
	public 	void setDtlProductId(Integer dtlproductid) {
		this.DtlProductId = dtlproductid;
	}

	// property: DtlTypeId
	
	private Integer DtlTypeId;
	public 	Integer getDtlTypeId() {
		return this.DtlTypeId;
	}
	public 	void setDtlTypeId(Integer dtltypeid) {
		this.DtlTypeId = dtltypeid;
	}

	// property: DtlActionId
	
	private Integer DtlActionId;
	public 	Integer getDtlActionId() {
		return this.DtlActionId;
	}
	public 	void setDtlActionId(Integer dtlactionid) {
		this.DtlActionId = dtlactionid;
	}

	// property: DtlRetailAmount
	@LWIsRequired 
	private java.math.BigDecimal DtlRetailAmount;
	public 	java.math.BigDecimal getDtlRetailAmount() {
		return this.DtlRetailAmount;
	}
	public 	void setDtlRetailAmount(java.math.BigDecimal dtlretailamount) {
		this.DtlRetailAmount = dtlretailamount;
	}

	// property: DtlSaleAmount
	@LWIsRequired 
	private java.math.BigDecimal DtlSaleAmount;
	public 	java.math.BigDecimal getDtlSaleAmount() {
		return this.DtlSaleAmount;
	}
	public 	void setDtlSaleAmount(java.math.BigDecimal dtlsaleamount) {
		this.DtlSaleAmount = dtlsaleamount;
	}

	// property: DtlQuantity
	
	private Integer DtlQuantity;
	public 	Integer getDtlQuantity() {
		return this.DtlQuantity;
	}
	public 	void setDtlQuantity(Integer dtlquantity) {
		this.DtlQuantity = dtlquantity;
	}

	// property: DtlDiscountAmount
	@LWIsRequired 
	private java.math.BigDecimal DtlDiscountAmount;
	public 	java.math.BigDecimal getDtlDiscountAmount() {
		return this.DtlDiscountAmount;
	}
	public 	void setDtlDiscountAmount(java.math.BigDecimal dtldiscountamount) {
		this.DtlDiscountAmount = dtldiscountamount;
	}

	// property: DtlClearanceItem
	@LWIsRequired 
	private Integer DtlClearanceItem;
	public 	Integer getDtlClearanceItem() {
		return this.DtlClearanceItem;
	}
	public 	void setDtlClearanceItem(Integer dtlclearanceitem) {
		this.DtlClearanceItem = dtlclearanceitem;
	}

}