//------------------------------------------------------------------------------
// <autogenerated>
//     This code was generated by LoyaltyWare.
//
//     Changes to this file may cause incorrect behavior and will be lost if 
//     the code is regenerated.
// </autogenerated>
//------------------------------------------------------------------------------

package com.brierley.loyaltyware.clientlib.domainmodel.client;

import java.util.Date;
import com.brierley.loyaltyware.clientlib.annotations.*;
import com.brierley.loyaltyware.clientlib.domainmodel.LWClientDataObject;

public class TxnLineItemDiscount extends LWClientDataObject {			    
	// property: TxnDiscountId
	@LWIsRequired @LWStringLength(50) 
	private String TxnDiscountId;
	public 	String getTxnDiscountId() {
		return this.TxnDiscountId;
	}
	public 	void setTxnDiscountId(String txndiscountid) {
		this.TxnDiscountId = txndiscountid;
	}

	// property: TxnHeaderId
	@LWIsRequired @LWStringLength(50) 
	private String TxnHeaderId;
	public 	String getTxnHeaderId() {
		return this.TxnHeaderId;
	}
	public 	void setTxnHeaderId(String txnheaderid) {
		this.TxnHeaderId = txnheaderid;
	}

	// property: TxnDate
	@LWIsRequired 
	private Date TxnDate;
	public 	Date getTxnDate() {
		return this.TxnDate;
	}
	public 	void setTxnDate(Date txndate) {
		this.TxnDate = txndate;
	}

	// property: TxnDetailId
	@LWStringLength(50) 
	private String TxnDetailId;
	public 	String getTxnDetailId() {
		return this.TxnDetailId;
	}
	public 	void setTxnDetailId(String txndetailid) {
		this.TxnDetailId = txndetailid;
	}

	// property: DiscountType
	@LWStringLength(25) 
	private String DiscountType;
	public 	String getDiscountType() {
		return this.DiscountType;
	}
	public 	void setDiscountType(String discounttype) {
		this.DiscountType = discounttype;
	}

	// property: DiscountAmount
	
	private java.math.BigDecimal DiscountAmount;
	public 	java.math.BigDecimal getDiscountAmount() {
		return this.DiscountAmount;
	}
	public 	void setDiscountAmount(java.math.BigDecimal discountamount) {
		this.DiscountAmount = discountamount;
	}

	// property: TxnChannel
	@LWStringLength(100) 
	private String TxnChannel;
	public 	String getTxnChannel() {
		return this.TxnChannel;
	}
	public 	void setTxnChannel(String txnchannel) {
		this.TxnChannel = txnchannel;
	}

	// property: OfferCode
	@LWStringLength(50) 
	private String OfferCode;
	public 	String getOfferCode() {
		return this.OfferCode;
	}
	public 	void setOfferCode(String offercode) {
		this.OfferCode = offercode;
	}

}