//------------------------------------------------------------------------------
// <autogenerated>
//     This code was generated by LoyaltyWare.
//
//     Changes to this file may cause incorrect behavior and will be lost if 
//     the code is regenerated.
// </autogenerated>
//------------------------------------------------------------------------------

package com.brierley.loyaltyware.clientlib.domainmodel.client;

import java.util.Date;
import com.brierley.loyaltyware.clientlib.annotations.*;
import com.brierley.loyaltyware.clientlib.domainmodel.LWClientDataObject;

public class TxnRewardRedeem extends LWClientDataObject {			    
	// property: TxnHeaderId
	@LWIsRequired @LWStringLength(50) 
	private String TxnHeaderId;
	public 	String getTxnHeaderId() {
		return this.TxnHeaderId;
	}
	public 	void setTxnHeaderId(String txnheaderid) {
		this.TxnHeaderId = txnheaderid;
	}

	// property: TxnDate
	@LWIsRequired 
	private Date TxnDate;
	public 	Date getTxnDate() {
		return this.TxnDate;
	}
	public 	void setTxnDate(Date txndate) {
		this.TxnDate = txndate;
	}

	// property: TxnDetailId
	@LWStringLength(50) 
	private String TxnDetailId;
	public 	String getTxnDetailId() {
		return this.TxnDetailId;
	}
	public 	void setTxnDetailId(String txndetailid) {
		this.TxnDetailId = txndetailid;
	}

	// property: ProgramId
	
	private Integer ProgramId;
	public 	Integer getProgramId() {
		return this.ProgramId;
	}
	public 	void setProgramId(Integer programid) {
		this.ProgramId = programid;
	}

	// property: CertificateRedeemType
	@LWStringLength(3) 
	private String CertificateRedeemType;
	public 	String getCertificateRedeemType() {
		return this.CertificateRedeemType;
	}
	public 	void setCertificateRedeemType(String certificateredeemtype) {
		this.CertificateRedeemType = certificateredeemtype;
	}

	// property: CertificateCode
	@LWStringLength(50) 
	private String CertificateCode;
	public 	String getCertificateCode() {
		return this.CertificateCode;
	}
	public 	void setCertificateCode(String certificatecode) {
		this.CertificateCode = certificatecode;
	}

	// property: CertificateDiscountAmount
	
	private java.math.BigDecimal CertificateDiscountAmount;
	public 	java.math.BigDecimal getCertificateDiscountAmount() {
		return this.CertificateDiscountAmount;
	}
	public 	void setCertificateDiscountAmount(java.math.BigDecimal certificatediscountamount) {
		this.CertificateDiscountAmount = certificatediscountamount;
	}

}