//------------------------------------------------------------------------------
// <autogenerated>
//     This code was generated by LoyaltyWare.
//
//     Changes to this file may cause incorrect behavior and will be lost if 
//     the code is regenerated.
// </autogenerated>
//------------------------------------------------------------------------------

package com.brierley.loyaltyware.clientlib.domainmodel.client;

import java.util.Date;
import com.brierley.loyaltyware.clientlib.annotations.*;
import com.brierley.loyaltyware.clientlib.domainmodel.LWClientDataObject;

public class TxnTender extends LWClientDataObject {			    
	// property: RoundedAmount
	
	private Long RoundedAmount;
	public 	Long getRoundedAmount() {
		return this.RoundedAmount;
	}
	public 	void setRoundedAmount(Long roundedamount) {
		this.RoundedAmount = roundedamount;
	}

	// property: TxnDate
	
	private Date TxnDate;
	public 	Date getTxnDate() {
		return this.TxnDate;
	}
	public 	void setTxnDate(Date txndate) {
		this.TxnDate = txndate;
	}

	// property: TxnStoreId
	
	private Integer TxnStoreId;
	public 	Integer getTxnStoreId() {
		return this.TxnStoreId;
	}
	public 	void setTxnStoreId(Integer txnstoreid) {
		this.TxnStoreId = txnstoreid;
	}

	// property: TxnTenderId
	@LWIsRequired @LWStringLength(50) 
	private String TxnTenderId;
	public 	String getTxnTenderId() {
		return this.TxnTenderId;
	}
	public 	void setTxnTenderId(String txntenderid) {
		this.TxnTenderId = txntenderid;
	}

	// property: TxnHeaderId
	@LWIsRequired @LWStringLength(50) 
	private String TxnHeaderId;
	public 	String getTxnHeaderId() {
		return this.TxnHeaderId;
	}
	public 	void setTxnHeaderId(String txnheaderid) {
		this.TxnHeaderId = txnheaderid;
	}

	// property: TenderType
	@LWIsRequired 
	private Integer TenderType;
	public 	Integer getTenderType() {
		return this.TenderType;
	}
	public 	void setTenderType(Integer tendertype) {
		this.TenderType = tendertype;
	}

	// property: TenderAmount
	@LWIsRequired 
	private java.math.BigDecimal TenderAmount;
	public 	java.math.BigDecimal getTenderAmount() {
		return this.TenderAmount;
	}
	public 	void setTenderAmount(java.math.BigDecimal tenderamount) {
		this.TenderAmount = tenderamount;
	}

	// property: TenderCurrency
	@LWStringLength(20) 
	private String TenderCurrency;
	public 	String getTenderCurrency() {
		return this.TenderCurrency;
	}
	public 	void setTenderCurrency(String tendercurrency) {
		this.TenderCurrency = tendercurrency;
	}

	// property: TenderTaxAmount
	@LWIsRequired 
	private java.math.BigDecimal TenderTaxAmount;
	public 	java.math.BigDecimal getTenderTaxAmount() {
		return this.TenderTaxAmount;
	}
	public 	void setTenderTaxAmount(java.math.BigDecimal tendertaxamount) {
		this.TenderTaxAmount = tendertaxamount;
	}

	// property: TenderTaxRate
	@LWIsRequired 
	private java.math.BigDecimal TenderTaxRate;
	public 	java.math.BigDecimal getTenderTaxRate() {
		return this.TenderTaxRate;
	}
	public 	void setTenderTaxRate(java.math.BigDecimal tendertaxrate) {
		this.TenderTaxRate = tendertaxrate;
	}

}