using System;

using Brierley.FrameWork.Common;
using Brierley.FrameWork.Data.ModelAttributes;

namespace Brierley.FrameWork.Data.DomainModel
{
	/// <summary>
	/// POCO for MemberCoupon. This class is autogenerated
	/// </summary>
	[Serializable]
	[PetaPoco.ExplicitColumns]
	[PetaPoco.PrimaryKey("ID", sequenceName = "hibernate_sequence")]
	[PetaPoco.TableName("LW_MemberCoupon")]
    [AuditLog(false)]
	public class MemberCoupon : LWCoreObjectBase
	{
		/// <summary>
		/// Gets or sets the ID for the current MemberCoupon
		/// </summary>
        [PetaPoco.Column(IsNullable = false)]
		public long ID { get; set; }

		/// <summary>
		/// Gets or sets the CouponDefId for the current MemberCoupon
		/// </summary>
        [PetaPoco.Column(IsNullable = false)]
        [ForeignKey(typeof(CouponDef), "Id")]
		public long CouponDefId { get; set; }

		/// <summary>
		/// Gets or sets the CertificateNmbr for the current MemberCoupon
		/// </summary>
        [PetaPoco.Column(Length = 50)]
		public string CertificateNmbr { get; set; }

		/// <summary>
		/// Gets or sets the MemberId for the current MemberCoupon
		/// </summary>
        [PetaPoco.Column(IsNullable = false)]
        [ColumnIndex]
		public long MemberId { get; set; }

		/// <summary>
		/// Gets or sets the TimesUsed for the current MemberCoupon
		/// </summary>
        [PetaPoco.Column(IsNullable = false)]
		public long TimesUsed { get; set; }

		/// <summary>
		/// Gets or sets the DateIssued for the current MemberCoupon
		/// </summary>
        [PetaPoco.Column(IsNullable = false)]
		public DateTime DateIssued { get; set; }

		/// <summary>
		/// Gets or sets the DateRedeemed for the current MemberCoupon
		/// </summary>
        [PetaPoco.Column]
		public DateTime? DateRedeemed { get; set; }

        /// <summary>
        /// Gets or sets the StartDate for the current MemberCoupon
        /// </summary>
        [PetaPoco.Column(IsNullable = false)]
        public DateTime StartDate { get; set; }

		/// <summary>
		/// Gets or sets the ExpiryDate for the current MemberCoupon
		/// </summary>
        [PetaPoco.Column]
		public DateTime? ExpiryDate { get; set; }

		/// <summary>
		/// Gets or sets the display order for the current MemberCoupon
		/// </summary>
        [PetaPoco.Column]
		public int? DisplayOrder { get; set; }

		/// <summary>
		/// Gets or sets the CampaignId of the campaign that loaded this for the current MemberCoupon
		/// </summary>
        [PetaPoco.Column]
		public long? CampaignId { get; set; }

		/// <summary>
		/// Gets or sets the Status of the campaign that loaded this for the current MemberCoupon
		/// </summary>
        [PetaPoco.Column(Length = 25, IsNullable = true, PersistEnumAsString = true)]
		public CouponStatus? Status { get; set; }

		/// <summary>
		/// Gets or sets the Id of the MTouch associated with this coupon.
		/// </summary>
        [PetaPoco.Column]
		public long? MTouchId { get; set; }

		/// <summary>
		/// Initializes a new instance of the MemberCoupon class
		/// </summary>
		public MemberCoupon()
		{
			DateIssued = DateTime.Now;
		}

		public bool HasStarted(DateTime? onDate = null)
		{
			if (!onDate.HasValue)
			{
				onDate = DateTime.Now;
			}
			return StartDate <= onDate;
		}

		public bool HasExpired(DateTime? onDate = null)
		{
			if (!onDate.HasValue)
			{
				onDate = DateTime.Now;
			}
			return ExpiryDate.HasValue && onDate >= ExpiryDate.Value;
		}

		public bool IsActive(DateTime? onDate = null)
		{
			return Status != CouponStatus.Killed && HasStarted(onDate) && !HasExpired(onDate);
		}


		public override LWObjectAuditLogBase GetArchiveObject()
		{
			MemberCoupon_AL ar = new MemberCoupon_AL()
			{
				ObjectId = this.ID,
				CouponDefId = this.CouponDefId,
				CertificateNmbr = this.CertificateNmbr,
				MemberId = this.MemberId,
				TimesUsed = this.TimesUsed,
				DateIssued = this.DateIssued,
				DateRedeemed = this.DateRedeemed,
				ExpiryDate = this.ExpiryDate,
				DisplayOrder = this.DisplayOrder,
				CampaignId = this.CampaignId,
				Status = this.Status,
				MTouchId = this.MTouchId,
				CreateDate = this.CreateDate,
				UpdateDate = this.UpdateDate
			};
			return ar;
		}
	}
}