using Brierley.FrameWork.Data.ModelAttributes;
using System;

namespace Brierley.FrameWork.Data.DomainModel
{
	/// <summary>
	/// POCO for ClientConfiguration. This class is autogenerated
	/// </summary>
	[Serializable]
	[PetaPoco.ExplicitColumns]
	[PetaPoco.PrimaryKey("CKey", autoIncrement = false)]
	[PetaPoco.TableName("LW_ClientConfiguration")]
    [AuditLog(true)]
	public class ClientConfiguration : LWCoreObjectBase
	{
		/// <summary>
		/// Gets or sets the Key for the current ClientConfiguration
		/// </summary>
		[PetaPoco.Column("CKey", Length = 100, IsNullable = false)]
		public string Key { get; set; }

		/// <summary>
		/// Gets or sets the Value for the current ClientConfiguration
		/// </summary>
        [PetaPoco.Column(IsNullable = false)]
		public string Value { get; set; }

		/// <summary>
		/// Gets or sets the folder id for the current CouponDef
		/// </summary>
        [PetaPoco.Column]
        [ColumnIndex]
		public long? FolderId { get; set; }

		/// <summary>
		/// Gets or sets the ExternalValue for the current ClientConfiguration
		/// </summary>
        [PetaPoco.Column(IsNullable = false)]
		public bool ExternalValue { get; set; }


		/// <summary>
		/// Initializes a new instance of the ClientConfiguration class
		/// </summary>
		public ClientConfiguration()
		{
		}

		public override LWObjectAuditLogBase GetArchiveObject()
		{
			ClientConfiguration_AL ar = new ClientConfiguration_AL()
			{
				Key = this.Key,
				Value = this.Value,
				ExternalValue = this.ExternalValue,
				CreateDate = this.CreateDate,
				UpdateDate = this.UpdateDate
			};
			return ar;
		}
	}
}