using System;

using Brierley.FrameWork.Common;
using Brierley.FrameWork.Data.ModelAttributes;

namespace Brierley.FrameWork.Data.DomainModel
{
	/// <summary>
	/// POCO for ContentAttribute. This class is autogenerated
	/// </summary>
	[Serializable]
	[PetaPoco.ExplicitColumns]
	[PetaPoco.PrimaryKey("ID", sequenceName = "hibernate_sequence")]
	[PetaPoco.TableName("LW_ContentAttribute")]
    [AuditLog(true)]
    [ColumnIndex(ColumnName = "RefId,ContentType")]
    public class ContentAttribute : LWCoreObjectBase
	{
		/// <summary>
		/// Gets or sets the ID for the current ContentAttribute
		/// </summary>
        [PetaPoco.Column(IsNullable = false)]
		public long ID { get; set; }

		/// <summary>
		/// Gets or sets the ContentType for the current ContentAttribute
		/// </summary>
        [PetaPoco.Column(Length = 25, PersistEnumAsString = true, IsNullable = false)]
		public ContentObjType ContentType { get; set; }

		/// <summary>
		/// Gets or sets the RewardId for the current ContentAttribute
		/// </summary>
        [PetaPoco.Column(IsNullable = false)]
		public long RefId { get; set; }

		/// <summary>
		/// Gets or sets the ContentAttributeDefId for the current ContentAttribute
		/// </summary>
        [PetaPoco.Column(IsNullable = false)]
        [ForeignKey(typeof(ContentAttributeDef), "ID")]
		public long ContentAttributeDefId { get; set; }

		/// <summary>
		/// Gets or sets the Value for the current ContentAttribute
		/// </summary>
        [PetaPoco.Column("AttributeValue", Length = 2000)]
		public string Value { get; set; }


		/// <summary>
		/// Initializes a new instance of the ContentAttribute class
		/// </summary>
		public ContentAttribute()
		{
		}
		
		public override LWObjectAuditLogBase GetArchiveObject()
		{
			ContentAttribute_AL ar = new ContentAttribute_AL()
			{
				ObjectId = this.ID,
				ContentType = this.ContentType,
				ContentAttributeDefId = this.ContentAttributeDefId,
				RefId = this.RefId,
				Value = this.Value
			};
			return ar;
		}
	}
}