using System;
using System.Collections.Generic;

using Brierley.FrameWork.Common;
using Brierley.FrameWork.Data.ModelAttributes;

namespace Brierley.FrameWork.Data.DomainModel
{
    /// <summary>
    /// POCO for PromotionCertificate. This class is autogenerated
    /// </summary>
    [Serializable]
    [PetaPoco.ExplicitColumns]
    [PetaPoco.PrimaryKey("CertNmbr", autoIncrement = false)]
    [PetaPoco.TableName("LW_PromotionCertificate")]
    [ColumnIndex(ColumnName = "ObjectType,TypeCode,Available")]
	public class PromotionCertificate : LWCoreObjectBase
	{
		/// <summary>
		/// Gets or sets the CertNmbr for the current PromotionCertificate
		/// </summary>
        [PetaPoco.Column(Length = 50, IsNullable = false)]
		public string CertNmbr { get; set; }

		/// <summary>
		/// Gets or sets the TypeCode for the current PromotionCertificate
		/// </summary>
        [PetaPoco.Column(Length = 150, IsNullable = false)]
		public string TypeCode { get; set; }

		/// <summary>
		/// Gets or sets the ObjectType for the current PromotionCertificate
		/// </summary>
        [PetaPoco.Column(Length = 25, IsNullable = false, PersistEnumAsString = true)]
		public ContentObjType ObjectType { get; set; }

		/// <summary>
		/// Gets or sets the Available for the current PromotionCertificate
		/// </summary>
		[PetaPoco.Column(IsNullable = false)]
		public bool Available { get; set; }

		/// <summary>
		/// Gets or sets the StartDate for the current PromotionCertificate
		/// </summary>
		[PetaPoco.Column]
		public DateTime? StartDate { get; set; }

		/// <summary>
		/// Gets or sets the ExpiryDate for the current PromotionCertificate
		/// </summary>
		[PetaPoco.Column]
		public DateTime? ExpiryDate { get; set; }
	}
}