//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Brierley.FrameWork.IntelligentSearch {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://loyaltyware.brierley.com/", ConfigurationName="IntelligentSearch.CorrectAddressServicePortType")]
    public interface CorrectAddressServicePortType {
        
        // CODEGEN: Generating message contract since the wrapper namespace (http://loyaltyware.brierley.com/xsd) of message getCleanAddressRequest does not match the default value (http://loyaltyware.brierley.com/)
        [System.ServiceModel.OperationContractAttribute(Action="urn:getCleanAddress", ReplyAction="urn:getCleanAddressResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        Brierley.FrameWork.IntelligentSearch.getCleanAddressResponse getCleanAddress(Brierley.FrameWork.IntelligentSearch.getCleanAddressRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ws.apache.org/axis2/xsd")]
    public partial class LWCAAddress : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string cityField;
        
        private string countryField;
        
        private string countyField;
        
        private string dpvField;
        
        private string errorCodeField;
        
        private double latitudeField;
        
        private bool latitudeFieldSpecified;
        
        private string lineOneField;
        
        private double longitudeField;
        
        private bool longitudeFieldSpecified;
        
        private int returnCodeField;
        
        private bool returnCodeFieldSpecified;
        
        private string stateOrProvinceField;
        
        private string zipOrPostalCodeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=0)]
        public string city {
            get {
                return this.cityField;
            }
            set {
                this.cityField = value;
                this.RaisePropertyChanged("city");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=1)]
        public string country {
            get {
                return this.countryField;
            }
            set {
                this.countryField = value;
                this.RaisePropertyChanged("country");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=2)]
        public string county {
            get {
                return this.countyField;
            }
            set {
                this.countyField = value;
                this.RaisePropertyChanged("county");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string dpv {
            get {
                return this.dpvField;
            }
            set {
                this.dpvField = value;
                this.RaisePropertyChanged("dpv");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=4)]
        public string errorCode {
            get {
                return this.errorCodeField;
            }
            set {
                this.errorCodeField = value;
                this.RaisePropertyChanged("errorCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public double latitude {
            get {
                return this.latitudeField;
            }
            set {
                this.latitudeField = value;
                this.RaisePropertyChanged("latitude");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool latitudeSpecified {
            get {
                return this.latitudeFieldSpecified;
            }
            set {
                this.latitudeFieldSpecified = value;
                this.RaisePropertyChanged("latitudeSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=6)]
        public string lineOne {
            get {
                return this.lineOneField;
            }
            set {
                this.lineOneField = value;
                this.RaisePropertyChanged("lineOne");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public double longitude {
            get {
                return this.longitudeField;
            }
            set {
                this.longitudeField = value;
                this.RaisePropertyChanged("longitude");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool longitudeSpecified {
            get {
                return this.longitudeFieldSpecified;
            }
            set {
                this.longitudeFieldSpecified = value;
                this.RaisePropertyChanged("longitudeSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public int returnCode {
            get {
                return this.returnCodeField;
            }
            set {
                this.returnCodeField = value;
                this.RaisePropertyChanged("returnCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool returnCodeSpecified {
            get {
                return this.returnCodeFieldSpecified;
            }
            set {
                this.returnCodeFieldSpecified = value;
                this.RaisePropertyChanged("returnCodeSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=9)]
        public string stateOrProvince {
            get {
                return this.stateOrProvinceField;
            }
            set {
                this.stateOrProvinceField = value;
                this.RaisePropertyChanged("stateOrProvince");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=10)]
        public string zipOrPostalCode {
            get {
                return this.zipOrPostalCodeField;
            }
            set {
                this.zipOrPostalCodeField = value;
                this.RaisePropertyChanged("zipOrPostalCode");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getCleanAddress", WrapperNamespace="http://loyaltyware.brierley.com/xsd", IsWrapped=true)]
    public partial class getCleanAddressRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://loyaltyware.brierley.com/xsd", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public Brierley.FrameWork.IntelligentSearch.LWCAAddress addressIn;
        
        public getCleanAddressRequest() {
        }
        
        public getCleanAddressRequest(Brierley.FrameWork.IntelligentSearch.LWCAAddress addressIn) {
            this.addressIn = addressIn;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getCleanAddressResponse", WrapperNamespace="http://loyaltyware.brierley.com/xsd", IsWrapped=true)]
    public partial class getCleanAddressResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://loyaltyware.brierley.com/xsd", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public Brierley.FrameWork.IntelligentSearch.LWCAAddress @return;
        
        public getCleanAddressResponse() {
        }
        
        public getCleanAddressResponse(Brierley.FrameWork.IntelligentSearch.LWCAAddress @return) {
            this.@return = @return;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface CorrectAddressServicePortTypeChannel : Brierley.FrameWork.IntelligentSearch.CorrectAddressServicePortType, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class CorrectAddressServicePortTypeClient : System.ServiceModel.ClientBase<Brierley.FrameWork.IntelligentSearch.CorrectAddressServicePortType>, Brierley.FrameWork.IntelligentSearch.CorrectAddressServicePortType {
        
        public CorrectAddressServicePortTypeClient() {
        }
        
        public CorrectAddressServicePortTypeClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public CorrectAddressServicePortTypeClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CorrectAddressServicePortTypeClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CorrectAddressServicePortTypeClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Brierley.FrameWork.IntelligentSearch.getCleanAddressResponse Brierley.FrameWork.IntelligentSearch.CorrectAddressServicePortType.getCleanAddress(Brierley.FrameWork.IntelligentSearch.getCleanAddressRequest request) {
            return base.Channel.getCleanAddress(request);
        }
        
        public Brierley.FrameWork.IntelligentSearch.LWCAAddress getCleanAddress(Brierley.FrameWork.IntelligentSearch.LWCAAddress addressIn) {
            Brierley.FrameWork.IntelligentSearch.getCleanAddressRequest inValue = new Brierley.FrameWork.IntelligentSearch.getCleanAddressRequest();
            inValue.addressIn = addressIn;
            Brierley.FrameWork.IntelligentSearch.getCleanAddressResponse retVal = ((Brierley.FrameWork.IntelligentSearch.CorrectAddressServicePortType)(this)).getCleanAddress(inValue);
            return retVal.@return;
        }
    }
}
