//------------------------------------------------------------------------------
// <autogenerated>
//     This code was generated by LoyaltyWare.
//
//     Changes to this file may cause incorrect behavior and will be lost if 
//     the code is regenerated.
// </autogenerated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

namespace Brierley.LoyaltyWare.ClientLib
{
    [Serializable]
    public class LWClientException : ApplicationException
    {
        public int ErrorCode { get; set; }
        public double ElapsedTime { get; set; }
        public LWClientException() : base() { }
        public LWClientException(string message) : base(message) { }
        public LWClientException(string message, Exception exception) : base(message, exception) { }
    }
}
