//------------------------------------------------------------------------------
// <autogenerated>
//     This code was generated by LoyaltyWare.
//
//     Changes to this file may cause incorrect behavior and will be lost if 
//     the code is regenerated.
// </autogenerated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.IO;

namespace Brierley.LoyaltyWare.ClientLib
{
    public class LWLogger
    {
        #region Fields        
        private bool _toConsole = false;
        private StreamWriter _writer = null;
        #endregion

        #region Initialization
        public LWLogger(bool toConsole, string outputFile)
        {
            _toConsole = toConsole;
            if (!string.IsNullOrEmpty(outputFile))
	                {
	                    _writer = new StreamWriter(File.Open(outputFile, FileMode.OpenOrCreate));
            }
        }
        #endregion

        #region Helpers
        private void WriteToConsole(string message)
        {
            if (_toConsole)
            {
                Console.Out.WriteLine(message);
            }
        }

        private void WriteToFile(string message)
        {
            if (_writer != null)
            {
                try
                {
                    _writer.WriteLine(message);
                }
                catch (Exception ex)
                {
                    WriteToConsole("ERROR Writing to file.");
                    WriteToConsole(ex.Message);
                    WriteToConsole(ex.StackTrace);
                }
                finally
                {
                    if (_writer != null)
                    {
                         _writer.Flush();
                    }
                }                
            }
        }
        #endregion

        #region Methods
        public void WriteMessage(string message)
        {
            WriteToConsole(message);
            WriteToFile(message);
        }
        
	public void Dispose()
        {
            if (_writer != null)
            {
                _writer.Close();
                _writer = null;
            }
        }        
        #endregion
    }
}
