//------------------------------------------------------------------------------
// <autogenerated>
//     This code was generated by LoyaltyWare.
//
//     Changes to this file may cause incorrect behavior and will be lost if 
//     the code is regenerated.
// </autogenerated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;

using Brierley.LoyaltyWare.ClientLib;
//using Brierley.LoyaltyWare.ClientLib.DomainModel;
using Brierley.LoyaltyWare.ClientLib.DomainModel.Framework;

namespace Brierley.LoyaltyWare.ClientLib.DomainModel.Client
{
	public class AccountActivitySummaryStruct
	{							    											    
		#region Properties
		[LWMeta(true,0)]        								
		public virtual string TxnHeaderId { get; set; }			
		[LWMeta(false)]        								
		public virtual DateTime? TxnDate { get; set; }			
		[LWMeta(false,0)]        								
		public virtual string TxnNumber { get; set; }			
		[LWMeta(false,0)]        								
		public virtual string TxnRegisterNumber { get; set; }			
		[LWMeta(false)]        								
		public virtual TxnStoreInfoStruct TxnStoreInfo { get; set; }			
		[LWMeta(false)]        								
		public virtual decimal? TxnAmount { get; set; }			
		[LWMeta(false,0)]        								
		public virtual string TxnChannel { get; set; }			
		[LWMeta(false)]        								
		public virtual PointsHistoryStruct[] PointsHistory { get; set; }			
		[LWMeta(false)]        								
		public virtual AdditionalAttributesStruct[] AdditionalAttributes { get; set; }			
		#endregion				
	}
}
