//------------------------------------------------------------------------------
// <autogenerated>
//     This code was generated by LoyaltyWare.
//
//     Changes to this file may cause incorrect behavior and will be lost if 
//     the code is regenerated.
// </autogenerated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;

using Brierley.LoyaltyWare.ClientLib;
//using Brierley.LoyaltyWare.ClientLib.DomainModel;
using Brierley.LoyaltyWare.ClientLib.DomainModel.Framework;

namespace Brierley.LoyaltyWare.ClientLib.DomainModel.Client
{
	public class AccountActivityDetailsStruct
	{							    											    
		#region Properties
		[LWMeta(false,0)]        								
		public virtual string ItemDescription { get; set; }			
		[LWMeta(false)]        								
		public virtual int? Quantity { get; set; }			
		[LWMeta(true)]        								
		public virtual decimal SaleAmount { get; set; }			
		[LWMeta(false,0)]        								
		public virtual string ClassDescription { get; set; }			
		[LWMeta(false,0)]        								
		public virtual string ClassCode { get; set; }			
		[LWMeta(false)]        								
		public virtual PointsHistoryStruct[] PointsHistory { get; set; }			
		[LWMeta(false)]        								
		public virtual AdditionalAttributesStruct[] AdditionalAttributes { get; set; }			
		#endregion				
	}
}
