//------------------------------------------------------------------------------
// <autogenerated>
//     This code was generated by LoyaltyWare.
//
//     Changes to this file may cause incorrect behavior and will be lost if 
//     the code is regenerated.
// </autogenerated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;

using Brierley.LoyaltyWare.ClientLib;
//using Brierley.LoyaltyWare.ClientLib.DomainModel;
using Brierley.LoyaltyWare.ClientLib.DomainModel.Framework;

namespace Brierley.LoyaltyWare.ClientLib.DomainModel.Client
{
	public class AEPOSGetAccountSummaryOut
	{							    											    
		#region Properties
		[LWMeta(false,0)]        								
		public virtual string LoyaltyNumber { get; set; }			
		[LWMeta(false,0)]        								
		public virtual string FirstName { get; set; }			
		[LWMeta(false,0)]        								
		public virtual string LastName { get; set; }			
		[LWMeta(false,0)]        								
		public virtual string AddressLineOne { get; set; }			
		[LWMeta(false,0)]        								
		public virtual string AddressLineTwo { get; set; }			
		[LWMeta(false,0)]        								
		public virtual string City { get; set; }			
		[LWMeta(false,0)]        								
		public virtual string State { get; set; }			
		[LWMeta(false,0)]        								
		public virtual string PostalCode { get; set; }			
		[LWMeta(false,0)]        								
		public virtual string CountryCode { get; set; }			
		[LWMeta(false,0)]        								
		public virtual string HomePhone { get; set; }			
		[LWMeta(false,0)]        								
		public virtual string MobilePhone { get; set; }			
		[LWMeta(false,0)]        								
		public virtual string SMSOptIn { get; set; }			
		[LWMeta(false,0)]        								
		public virtual string Gender { get; set; }			
		[LWMeta(false,0)]        								
		public virtual string LanguagePreference { get; set; }			
		[LWMeta(false,0)]        								
		public virtual string DollarRewardMember { get; set; }			
		[LWMeta(false,0)]        								
		public virtual string EnrollmentDate { get; set; }			
		[LWMeta(false,0)]        								
		public virtual string StartingPoints { get; set; }			
		[LWMeta(false,0)]        								
		public virtual string BasicPoints { get; set; }			
		[LWMeta(false,0)]        								
		public virtual string BonusPoints { get; set; }			
		[LWMeta(false,0)]        								
		public virtual string PointsPerMonth { get; set; }			
		[LWMeta(false,0)]        								
		public virtual string TotalPoints { get; set; }			
		[LWMeta(false,0)]        								
		public virtual string PointsNeeded { get; set; }			
		[LWMeta(false,0)]        								
		public virtual string RewardLevel { get; set; }			
		[LWMeta(false,0)]        								
		public virtual string BaseBrand { get; set; }			
		[LWMeta(false,0)]        								
		public virtual string CurrentBrasPurchased { get; set; }			
		[LWMeta(false,0)]        								
		public virtual string CurrentBrasEarned { get; set; }			
		[LWMeta(false,0)]        								
		public virtual string FreeBrasMailed { get; set; }			
		[LWMeta(false,0)]        								
		public virtual string LastFreeBraMailedDate { get; set; }			
		[LWMeta(false,0)]        								
		public virtual string BraHomeDate { get; set; }			
		[LWMeta(false,0)]        								
		public virtual string FreeBraRedeemedDate { get; set; }			
		[LWMeta(false,0)]        								
		public virtual string StartDate { get; set; }			
		[LWMeta(false,0)]        								
		public virtual string EndDate { get; set; }			
		#endregion				
	}
}
