//------------------------------------------------------------------------------
// <autogenerated>
//     This code was generated by LoyaltyWare.
//
//     Changes to this file may cause incorrect behavior and will be lost if 
//     the code is regenerated.
// </autogenerated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;

using Brierley.LoyaltyWare.ClientLib;
//using Brierley.LoyaltyWare.ClientLib.DomainModel;
using Brierley.LoyaltyWare.ClientLib.DomainModel.Framework;

namespace Brierley.LoyaltyWare.ClientLib.DomainModel.Client
{
	public class AEPOSGetAccountActivityOut
	{							    											    
		#region Properties
		[LWMeta(true,0)]        								
		public virtual string LoyaltyNumber { get; set; }			
		[LWMeta(false)]        								
		public virtual int? TotalPageCount { get; set; }			
		[LWMeta(false,0)]        								
		public virtual string StartingPoints { get; set; }			
		[LWMeta(false,0)]        								
		public virtual string BasicPoints { get; set; }			
		[LWMeta(false,0)]        								
		public virtual string BonusPoints { get; set; }			
		[LWMeta(false,0)]        								
		public virtual string TotalPoints { get; set; }			
		[LWMeta(false,0)]        								
		public virtual string RewardLevel { get; set; }			
		[LWMeta(false,0)]        								
		public virtual string DollarRewardMember { get; set; }			
		[LWMeta(false,0)]        								
		public virtual string StartDate { get; set; }			
		[LWMeta(false,0)]        								
		public virtual string EndDate { get; set; }			
		[LWMeta(false)]        								
		public virtual TransactionHeadersStruct[] TransactionHeaders { get; set; }			
		#endregion				
	}
}
