//------------------------------------------------------------------------------
// <autogenerated>
//     This code was generated by LoyaltyWare.
//
//     Changes to this file may cause incorrect behavior and will be lost if 
//     the code is regenerated.
// </autogenerated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;

using Brierley.LoyaltyWare.ClientLib;
//using Brierley.LoyaltyWare.ClientLib.DomainModel;
using Brierley.LoyaltyWare.ClientLib.DomainModel.Framework;

namespace Brierley.LoyaltyWare.ClientLib.DomainModel.Client
{
	public class AwardLoyaltyCurrencyIn
	{							    											    
		#region Properties
		[LWMeta(true,255)]        								
		public virtual string CardID { get; set; }			
		[LWMeta(true,150)]        								
		public virtual string LoyaltyEvent { get; set; }			
		[LWMeta(true,150)]        								
		public virtual string LoyaltyCurrency { get; set; }			
		[LWMeta(false)]        								
		public virtual decimal? CurrencyAmount { get; set; }			
		[LWMeta(false)]        								
		public virtual DateTime? TransactionDate { get; set; }			
		[LWMeta(true)]        								
		public virtual DateTime ExpirationDate { get; set; }			
		[LWMeta(false,500)]        								
		public virtual string Note { get; set; }			
		[LWMeta(false,50)]        								
		public virtual string ChangedBy { get; set; }			
		#endregion				
	}
}
