//------------------------------------------------------------------------------
// <autogenerated>
//     This code was generated by LoyaltyWare.
//
//     Changes to this file may cause incorrect behavior and will be lost if 
//     the code is regenerated.
// </autogenerated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;

using Brierley.LoyaltyWare.ClientLib;
using Brierley.LoyaltyWare.ClientLib.DomainModel;

namespace Brierley.LoyaltyWare.ClientLib.DomainModel.Client
{
	public class BraPromoFulfillment : LWClientDataObject
	{							    											    
		#region Properties
		[LWMeta(false,50)]				
		public virtual string City { get; set; }			
		[LWMeta(false,50)]				
		public virtual string LoyaltyIDNumber { get; set; }			
		[LWMeta(false,50)]				
		public virtual string FirstName { get; set; }			
		[LWMeta(false,50)]				
		public virtual string LastName { get; set; }			
		[LWMeta(false,100)]				
		public virtual string AddressLineOne { get; set; }			
		[LWMeta(false,100)]				
		public virtual string AddressLineTwo { get; set; }			
		[LWMeta(false,50)]				
		public virtual string StateOrProvince { get; set; }			
		[LWMeta(false,25)]				
		public virtual string ZipOrPostalCode { get; set; }			
		[LWMeta(false,25)]				
		public virtual string Country { get; set; }			
		[LWMeta(false)]				
		public virtual long? ReasonCode { get; set; }			
		[LWMeta(false)]				
		public virtual long? NumberOfCerts { get; set; }			
		[LWMeta(false,20)]				
		public virtual string LanguagePreference { get; set; }			
		[LWMeta(false)]				
		public virtual long? IsUnderAge { get; set; }			
		[LWMeta(false)]				
		public virtual long? PurchasedAEBrand { get; set; }			
		[LWMeta(false)]				
		public virtual long? PurchasedAerieBrand { get; set; }			
		[LWMeta(false)]				
		public virtual long? PurchasedKidsBrand { get; set; }			
		[LWMeta(false,10)]				
		public virtual string BaseLoyaltyBrand { get; set; }			
		#endregion				
	}
}
