//------------------------------------------------------------------------------
// <autogenerated>
//     This code was generated by LoyaltyWare.
//
//     Changes to this file may cause incorrect behavior and will be lost if 
//     the code is regenerated.
// </autogenerated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;

using Brierley.LoyaltyWare.ClientLib;
using Brierley.LoyaltyWare.ClientLib.DomainModel;

namespace Brierley.LoyaltyWare.ClientLib.DomainModel.Client
{
	public class CatalogSearchAttributesStruct
	{							    											    
		#region Properties
		[LWMeta(true,50)]        								
		public virtual string AttributeName { get; set; }			
		[LWMeta(true,256)]        								
		public virtual string AttributeValue { get; set; }			
		#endregion				
	}
}
