//------------------------------------------------------------------------------
// <autogenerated>
//     This code was generated by LoyaltyWare.
//
//     Changes to this file may cause incorrect behavior and will be lost if 
//     the code is regenerated.
// </autogenerated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;

using Brierley.LoyaltyWare.ClientLib;
//using Brierley.LoyaltyWare.ClientLib.DomainModel;
using Brierley.LoyaltyWare.ClientLib.DomainModel.Framework;

namespace Brierley.LoyaltyWare.ClientLib.DomainModel.Client
{
	public class GetAccountSummaryOut
	{							    											    
		#region Properties
		[LWMeta(true)]        								
		public virtual decimal CurrencyBalance { get; set; }			
		[LWMeta(true,0)]        								
		public virtual string MemberStatus { get; set; }			
		[LWMeta(true)]        								
		public virtual DateTime MemberAddDate { get; set; }			
		[LWMeta(false,0)]        								
		public virtual string CurrentTierName { get; set; }			
		[LWMeta(false)]        								
		public virtual DateTime? CurrentTierExpirationDate { get; set; }			
		[LWMeta(false)]        								
		public virtual decimal? CurrencyToNextTier { get; set; }			
		[LWMeta(false)]        								
		public virtual decimal? CurrencyToNextReward { get; set; }			
		[LWMeta(false)]        								
		public virtual DateTime? LastActivityDate { get; set; }			
		#endregion				
	}
}
