//------------------------------------------------------------------------------
// <autogenerated>
//     This code was generated by LoyaltyWare.
//
//     Changes to this file may cause incorrect behavior and will be lost if 
//     the code is regenerated.
// </autogenerated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;

using Brierley.LoyaltyWare.ClientLib;
using Brierley.LoyaltyWare.ClientLib.DomainModel;

namespace Brierley.LoyaltyWare.ClientLib.DomainModel.Client
{
	public class GetPointTransactionsCountIn
	{							    											    
		#region Properties
		[LWMeta(true,0)]        								
		public virtual string MemberIdentity { get; set; }			
		[LWMeta(false,255)]        								
		public virtual string CardID { get; set; }			
		[LWMeta(false)]        								
		public virtual DateTime? StartDate { get; set; }			
		[LWMeta(false)]        								
		public virtual DateTime? EndDate { get; set; }			
		[LWMeta(false,150)]        								
		public virtual string[] LoyaltyCurrencyNames { get; set; }			
		[LWMeta(false,150)]        								
		public virtual string[] LoyaltyEventNames { get; set; }			
		#endregion				
	}
}
