//------------------------------------------------------------------------------
// <autogenerated>
//     This code was generated by LoyaltyWare.
//
//     Changes to this file may cause incorrect behavior and will be lost if 
//     the code is regenerated.
// </autogenerated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;

using Brierley.LoyaltyWare.ClientLib;
//using Brierley.LoyaltyWare.ClientLib.DomainModel;
using Brierley.LoyaltyWare.ClientLib.DomainModel.Framework;

namespace Brierley.LoyaltyWare.ClientLib.DomainModel.Client
{
	public class GetRewardCatalogIn
	{							    											    
		#region Properties
		[LWMeta(false)]        								
		public virtual bool? ActiveOnly { get; set; }			
		[LWMeta(false,50)]        								
		public virtual string Tier { get; set; }			
		[LWMeta(false,20)]        								
		public virtual string Language { get; set; }			
		[LWMeta(false)]        								
		public virtual long? CategoryId { get; set; }			
		[LWMeta(false)]        								
		public virtual bool? ReturnRewardCategory { get; set; }			
		[LWMeta(false)]        								
		public virtual ContentSearchAttributesStruct[] ContentSearchAttributes { get; set; }			
		[LWMeta(false)]        								
		public virtual int? StartIndex { get; set; }			
		[LWMeta(false)]        								
		public virtual int? BatchSize { get; set; }			
		[LWMeta(false)]        								
		public virtual decimal? CurrencyToEarnLow { get; set; }			
		[LWMeta(false)]        								
		public virtual decimal? CurrencyToEarnHigh { get; set; }			
		#endregion				
	}
}
