//------------------------------------------------------------------------------
// <autogenerated>
//     This code was generated by LoyaltyWare.
//
//     Changes to this file may cause incorrect behavior and will be lost if 
//     the code is regenerated.
// </autogenerated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;

using Brierley.LoyaltyWare.ClientLib;
//using Brierley.LoyaltyWare.ClientLib.DomainModel;
using Brierley.LoyaltyWare.ClientLib.DomainModel.Framework;

namespace Brierley.LoyaltyWare.ClientLib.DomainModel.Client
{
	public class GetRewardCatalogItemStruct
	{							    											    
		#region Properties
		[LWMeta(true)]        								
		public virtual long RewardID { get; set; }			
		[LWMeta(true,0)]        								
		public virtual string RewardName { get; set; }			
		[LWMeta(false,0)]        								
		public virtual string TypeCode { get; set; }			
		[LWMeta(false,0)]        								
		public virtual string ShortDescription { get; set; }			
		[LWMeta(false,0)]        								
		public virtual string LongDescription { get; set; }			
		[LWMeta(false,0)]        								
		public virtual string LegalText { get; set; }			
		[LWMeta(false)]        								
		public virtual decimal? CurrencyToEarn { get; set; }			
		[LWMeta(false,0)]        								
		public virtual string SmallImageFile { get; set; }			
		[LWMeta(false,0)]        								
		public virtual string LargeImageFile { get; set; }			
		[LWMeta(false)]        								
		public virtual DateTime? CatalogStartDate { get; set; }			
		[LWMeta(false)]        								
		public virtual DateTime? CatalogEndDate { get; set; }			
		[LWMeta(false)]        								
		public virtual bool? Active { get; set; }			
		[LWMeta(false,0)]        								
		public virtual string LogoFileName { get; set; }			
		[LWMeta(false)]        								
		public virtual ProductStruct Product { get; set; }			
		[LWMeta(false)]        								
		public virtual ContentAttributesStruct[] ContentAttributes { get; set; }			
		#endregion				
	}
}
