//------------------------------------------------------------------------------
// <autogenerated>
//     This code was generated by LoyaltyWare.
//
//     Changes to this file may cause incorrect behavior and will be lost if 
//     the code is regenerated.
// </autogenerated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;

using Brierley.LoyaltyWare.ClientLib;
using Brierley.LoyaltyWare.ClientLib.DomainModel;

namespace Brierley.LoyaltyWare.ClientLib.DomainModel.Client
{
	public class GetSurveyIn
	{							    											    
		#region Properties
		[LWMeta(true)]        								
		public virtual long Entity { get; set; }			
		[LWMeta(false,0)]        								
		public virtual string SurveyName { get; set; }			
		[LWMeta(true,0)]        								
		public virtual string SurveyType { get; set; }			
		[LWMeta(true)]        								
		public virtual bool IsComplete { get; set; }			
		#endregion				
	}
}
