//------------------------------------------------------------------------------
// <autogenerated>
//     This code was generated by LoyaltyWare.
//
//     Changes to this file may cause incorrect behavior and will be lost if 
//     the code is regenerated.
// </autogenerated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;

using Brierley.LoyaltyWare.ClientLib;
using Brierley.LoyaltyWare.ClientLib.DomainModel;

namespace Brierley.LoyaltyWare.ClientLib.DomainModel.Client
{
	public class HistoryTxnTender : LWClientDataObject
	{							    											    
		#region Properties
		[LWMeta(false)]				
		public virtual DateTime? TxnDate { get; set; }			
		[LWMeta(false)]				
		public virtual long? ProcessID { get; set; }			
		[LWMeta(false,50)]				
		public virtual string StoreID { get; set; }			
		[LWMeta(true,50)]				
		public virtual string TxnHeaderID { get; set; }			
		[LWMeta(true,50)]				
		public virtual string TxnTenderID { get; set; }			
		[LWMeta(false)]				
		public virtual long? TenderType { get; set; }			
		[LWMeta(true)]				
		public virtual decimal TenderAmount { get; set; }			
		[LWMeta(false,20)]				
		public virtual string TenderCurrency { get; set; }			
		[LWMeta(false)]				
		public virtual decimal? TenderTax { get; set; }			
		[LWMeta(false)]				
		public virtual decimal? TenderTaxRate { get; set; }			
		[LWMeta(false,100)]				
		public virtual string ErrorMessage { get; set; }			
		[LWMeta(false)]				
		public virtual long? Vckey { get; set; }			
		[LWMeta(false)]				
		public virtual long? FileId { get; set; }			
		[LWMeta(false)]				
		public virtual long? FileLineItem { get; set; }			
		#endregion				
	}
}
