//------------------------------------------------------------------------------
// <autogenerated>
//     This code was generated by LoyaltyWare.
//
//     Changes to this file may cause incorrect behavior and will be lost if 
//     the code is regenerated.
// </autogenerated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;

using Brierley.LoyaltyWare.ClientLib;
using Brierley.LoyaltyWare.ClientLib.DomainModel;

namespace Brierley.LoyaltyWare.ClientLib.DomainModel.Client
{
	public class HistoryTxnDetail : LWClientDataObject
	{							    											    
		#region Properties
		[LWMeta(false,50)]				
		public virtual string TxnHeaderID { get; set; }			
		[LWMeta(false,50)]				
		public virtual string TxnDetailID { get; set; }			
		[LWMeta(false,50)]				
		public virtual string BrandID { get; set; }			
		[LWMeta(false)]				
		public virtual long? FileID { get; set; }			
		[LWMeta(false)]				
		public virtual long? FileLineItem { get; set; }			
		[LWMeta(false)]				
		public virtual long? CardID { get; set; }			
		[LWMeta(false)]				
		public virtual long? CreditCardID { get; set; }			
		[LWMeta(false,50)]				
		public virtual string TxnLoyaltyID { get; set; }			
		[LWMeta(false,50)]				
		public virtual string TxnMaskID { get; set; }			
		[LWMeta(true,25)]				
		public virtual string TxnNumber { get; set; }			
		[LWMeta(true)]				
		public virtual DateTime TxnDate { get; set; }			
		[LWMeta(false)]				
		public virtual DateTime? TxnDateModified { get; set; }			
		[LWMeta(true,15)]				
		public virtual string TxnRegisterNumber { get; set; }			
		[LWMeta(true,50)]				
		public virtual string TxnStoreID { get; set; }			
		[LWMeta(false,50)]				
		public virtual string TxnType { get; set; }			
		[LWMeta(true)]				
		public virtual decimal TxnAmount { get; set; }			
		[LWMeta(false)]				
		public virtual decimal? TxnDiscountAmount { get; set; }			
		[LWMeta(false,100)]				
		public virtual string TxnEmailAddress { get; set; }			
		[LWMeta(false,20)]				
		public virtual string TxnPhoneNumber { get; set; }			
		[LWMeta(false,25)]				
		public virtual string TxnEmployeeID { get; set; }			
		[LWMeta(false,100)]				
		public virtual string TxnChannelID { get; set; }			
		[LWMeta(false)]				
		public virtual long? TxnOriginalTxnRowKey { get; set; }			
		[LWMeta(false)]				
		public virtual long? TxnCreditsUsed { get; set; }			
		[LWMeta(false)]				
		public virtual long? DtlItemLineNbr { get; set; }			
		[LWMeta(false)]				
		public virtual long? DtlProductID { get; set; }			
		[LWMeta(false)]				
		public virtual long? DtlTypeID { get; set; }			
		[LWMeta(false)]				
		public virtual long? DtlActionID { get; set; }			
		[LWMeta(false)]				
		public virtual decimal? DtlRetailAmount { get; set; }			
		[LWMeta(false)]				
		public virtual decimal? DtlSaleAmount { get; set; }			
		[LWMeta(false)]				
		public virtual long? DtlQuantity { get; set; }			
		[LWMeta(false)]				
		public virtual decimal? DtlDiscountAmount { get; set; }			
		[LWMeta(false)]				
		public virtual long? DtlClearanceItem { get; set; }			
		[LWMeta(false)]				
		public virtual DateTime? DtlDateModified { get; set; }			
		[LWMeta(false)]				
		public virtual long? ReconcileStatus { get; set; }			
		[LWMeta(false)]				
		public virtual DateTime? ShipDate { get; set; }			
		[LWMeta(false,15)]				
		public virtual string OrderNumber { get; set; }			
		[LWMeta(false,50)]				
		public virtual string DtlClassCode { get; set; }			
		[LWMeta(false,100)]				
		public virtual string SKUNumber { get; set; }			
		[LWMeta(false)]				
		public virtual decimal? TenderAmount { get; set; }			
		[LWMeta(false)]				
		public virtual decimal? TxnQualPurchaseAmt { get; set; }			
		[LWMeta(false,100)]				
		public virtual string ErrorMessage { get; set; }			
		[LWMeta(false)]				
		public virtual long? Vckey { get; set; }			
		[LWMeta(false,10)]				
		public virtual string StoreNumber { get; set; }			
		[LWMeta(false)]				
		public virtual long? ProcessID { get; set; }			
		#endregion				
	}
}
