//------------------------------------------------------------------------------
// <autogenerated>
//     This code was generated by LoyaltyWare.
//
//     Changes to this file may cause incorrect behavior and will be lost if 
//     the code is regenerated.
// </autogenerated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;

using Brierley.LoyaltyWare.ClientLib;
using Brierley.LoyaltyWare.ClientLib.DomainModel;

namespace Brierley.LoyaltyWare.ClientLib.DomainModel.Client
{
	public class MemberMergeHistory : LWClientDataObject
	{							    											    
		#region Properties
		[LWMeta(false,50)]				
		public virtual string ChangedBy { get; set; }			
		[LWMeta(false,50)]				
		public virtual string FromLoyaltyID { get; set; }			
		[LWMeta(false)]				
		public virtual long? FromIPCode { get; set; }			
		#endregion				
	}
}
