//------------------------------------------------------------------------------
// <autogenerated>
//     This code was generated by LoyaltyWare.
//
//     Changes to this file may cause incorrect behavior and will be lost if 
//     the code is regenerated.
// </autogenerated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;

using Brierley.LoyaltyWare.ClientLib;
using Brierley.LoyaltyWare.ClientLib.DomainModel;

namespace Brierley.LoyaltyWare.ClientLib.DomainModel.Client
{
	public class MemberDetails : LWClientDataObject
	{							    											    
		#region Properties
		[LWMeta(false)]				
		public virtual bool? DirectMailOptIn { get; set; }			
		[LWMeta(false)]				
		public virtual bool? EmailOptIn { get; set; }			
		[LWMeta(false,20)]				
		public virtual string HHKey { get; set; }			
		[LWMeta(false,50)]				
		public virtual string OldCellNumber { get; set; }			
		[LWMeta(false)]				
		public virtual long? ExtendedPlayCode { get; set; }			
		[LWMeta(false)]				
		public virtual bool? EmailAddressMailable { get; set; }			
		[LWMeta(false,100)]				
		public virtual string AddressLineOne { get; set; }			
		[LWMeta(false,100)]				
		public virtual string AddressLineTwo { get; set; }			
		[LWMeta(false,100)]				
		public virtual string AddressLineThree { get; set; }			
		[LWMeta(false,100)]				
		public virtual string AddressLineFour { get; set; }			
		[LWMeta(false)]				
		public virtual bool? AITUpdate { get; set; }			
		[LWMeta(false)]				
		public virtual long? CardType { get; set; }			
		[LWMeta(false,255)]				
		public virtual string ChangedBy { get; set; }			
		[LWMeta(false)]				
		public virtual bool? PassValidation { get; set; }			
		[LWMeta(false,255)]				
		public virtual string EmailAddress { get; set; }			
		[LWMeta(false)]				
		public virtual long? BaseBrandID { get; set; }			
		[LWMeta(false,50)]				
		public virtual string City { get; set; }			
		[LWMeta(false,50)]				
		public virtual string StateOrProvince { get; set; }			
		[LWMeta(false,25)]				
		public virtual string ZipOrPostalCode { get; set; }			
		[LWMeta(false,50)]				
		public virtual string County { get; set; }			
		[LWMeta(false,50)]				
		public virtual string Country { get; set; }			
		[LWMeta(false)]				
		public virtual bool? AddressMailable { get; set; }			
		[LWMeta(false,25)]				
		public virtual string HomePhone { get; set; }			
		[LWMeta(false,25)]				
		public virtual string MobilePhone { get; set; }			
		[LWMeta(false,25)]				
		public virtual string WorkPhone { get; set; }			
		[LWMeta(false,255)]				
		public virtual string SecondaryEmailAddress { get; set; }			
		[LWMeta(false)]				
		public virtual int? MemberStatusCode { get; set; }			
		[LWMeta(false)]				
		public virtual DateTime? DirectMailOptInDate { get; set; }			
		[LWMeta(false)]				
		public virtual DateTime? EmailOptInDate { get; set; }			
		[LWMeta(false)]				
		public virtual DateTime? SMSOptInDate { get; set; }			
		[LWMeta(false)]				
		public virtual DateTime? EnrollDate { get; set; }			
		[LWMeta(false,10)]				
		public virtual string Gender { get; set; }			
		[LWMeta(false)]				
		public virtual int? MemberSource { get; set; }			
		[LWMeta(false,20)]				
		public virtual string LanguagePreference { get; set; }			
		[LWMeta(false,255)]				
		public virtual string SecurityQuestion { get; set; }			
		[LWMeta(false,255)]				
		public virtual string SecurityAnswer { get; set; }			
		[LWMeta(false,255)]				
		public virtual string OldEmailAddress { get; set; }			
		[LWMeta(false)]				
		public virtual int? HomeStoreID { get; set; }			
		[LWMeta(false)]				
		public virtual bool? HasEmailBonusCredit { get; set; }			
		[LWMeta(false)]				
		public virtual bool? IsUnderAge { get; set; }			
		[LWMeta(false)]				
		public virtual int? EmployeeCode { get; set; }			
		[LWMeta(false)]				
		public virtual bool? SMSOptIn { get; set; }			
		[LWMeta(false)]				
		public virtual long? LastBraStoreNumber { get; set; }			
		[LWMeta(false)]				
		public virtual long? LastPurchasePoints { get; set; }			
		[LWMeta(false)]				
		public virtual DateTime? LastBraPurchaseDate { get; set; }			
		[LWMeta(false)]				
		public virtual int? HasGWBonusCredit { get; set; }			
		[LWMeta(false)]				
		public virtual DateTime? BraFirstPurchaseDate { get; set; }			
		[LWMeta(false)]				
		public virtual DateTime? JeansFirstPurchaseDate { get; set; }			
		[LWMeta(false)]				
		public virtual int? GwObjVer { get; set; }			
		[LWMeta(false)]				
		public virtual int? GwLinked { get; set; }			
		[LWMeta(false)]				
		public virtual DateTime? NextEmailReminderDate { get; set; }			
		[LWMeta(false)]				
		public virtual DateTime? LastJeansPurchaseDate { get; set; }			
		[LWMeta(false,11)]				
		public virtual string StoreLastJeansPurchased { get; set; }			
		[LWMeta(false)]				
		public virtual long? AutoIssueReward { get; set; }			
		[LWMeta(false)]				
		public virtual long? PrimaryContact { get; set; }			
		[LWMeta(false)]				
		public virtual long? PendingCellVerification { get; set; }			
		[LWMeta(false)]				
		public virtual long? DownloadMobileApp { get; set; }			
		[LWMeta(false)]				
		public virtual long? PendingEmailVerification { get; set; }			
		[LWMeta(false)]				
		public virtual DateTime? CardOpenDate { get; set; }			
		[LWMeta(false)]				
		public virtual DateTime? programchangedate { get; set; }			
		[LWMeta(false)]				
		public virtual DateTime? CardCloseDate { get; set; }			
		[LWMeta(false)]				
		public virtual long? LifeTimeNetSpend { get; set; }			
		[LWMeta(false)]				
		public virtual long? NetSpend { get; set; }			
		[LWMeta(false)]				
		public virtual long? PrevNetSpend { get; set; }			
		[LWMeta(false)]				
		public virtual long? TerminationReasonID { get; set; }			
		[LWMeta(false)]				
		public virtual DateTime? EmailAddressUpdateDate { get; set; }			
		#endregion				
	}
}
