//------------------------------------------------------------------------------
// <autogenerated>
//     This code was generated by LoyaltyWare.
//
//     Changes to this file may cause incorrect behavior and will be lost if 
//     the code is regenerated.
// </autogenerated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;

using Brierley.LoyaltyWare.ClientLib;
using Brierley.LoyaltyWare.ClientLib.DomainModel;

namespace Brierley.LoyaltyWare.ClientLib.DomainModel.Client
{
	public class MemberReceipts : LWClientDataObject
	{							    											    
		#region Properties
		[LWMeta(false)]				
		public virtual long? ReceiptType { get; set; }			
		[LWMeta(false,50)]				
		public virtual string TxnStoreID { get; set; }			
		[LWMeta(false,10)]				
		public virtual string TxnRegisterNumber { get; set; }			
		[LWMeta(false,25)]				
		public virtual string TxnNumber { get; set; }			
		[LWMeta(false)]				
		public virtual DateTime? TxnDate { get; set; }			
		[LWMeta(false,15)]				
		public virtual string OrderNumber { get; set; }			
		[LWMeta(false)]				
		public virtual decimal? TenderAmount { get; set; }			
		[LWMeta(false)]				
		public virtual DateTime? ClosedDate { get; set; }			
		[LWMeta(false)]				
		public virtual DateTime? ExpirationDate { get; set; }			
		[LWMeta(false,50)]				
		public virtual string TxnHeaderID { get; set; }			
		[LWMeta(false,255)]				
		public virtual string CHANGEDBY { get; set; }			
		#endregion				
	}
}
