//------------------------------------------------------------------------------
// <autogenerated>
//     This code was generated by LoyaltyWare.
//
//     Changes to this file may cause incorrect behavior and will be lost if 
//     the code is regenerated.
// </autogenerated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;

using Brierley.LoyaltyWare.ClientLib;
using Brierley.LoyaltyWare.ClientLib.DomainModel;

namespace Brierley.LoyaltyWare.ClientLib.DomainModel.Client
{
	public class MemberProactiveMerge : LWClientDataObject
	{							    											    
		#region Properties
		[LWMeta(false,7)]				
		public virtual string AddressLineOne { get; set; }			
		[LWMeta(false)]				
		public virtual DateTime? MemberCreateDate { get; set; }			
		[LWMeta(false)]				
		public virtual long? MemberStatus { get; set; }			
		[LWMeta(false,50)]				
		public virtual string ChangedBy { get; set; }			
		[LWMeta(false,4)]				
		public virtual string FirstName { get; set; }			
		[LWMeta(false,50)]				
		public virtual string LastName { get; set; }			
		[LWMeta(false,20)]				
		public virtual string ZipCode { get; set; }			
		#endregion				
	}
}
