//------------------------------------------------------------------------------
// <autogenerated>
//     This code was generated by LoyaltyWare.
//
//     Changes to this file may cause incorrect behavior and will be lost if 
//     the code is regenerated.
// </autogenerated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;

using Brierley.LoyaltyWare.ClientLib;
using Brierley.LoyaltyWare.ClientLib.DomainModel;

namespace Brierley.LoyaltyWare.ClientLib.DomainModel.Client
{
	public class MemberRewardFulfillment : LWClientDataObject
	{							    											    
		#region Properties
		[LWMeta(false)]				
		public virtual long? PointBalance { get; set; }			
		[LWMeta(false,50)]				
		public virtual string RewardDescription { get; set; }			
		[LWMeta(false)]				
		public virtual long? PointsRedeemed { get; set; }			
		[LWMeta(false)]				
		public virtual long? EmployeeCode { get; set; }			
		[LWMeta(false)]				
		public virtual long? ExtendedPlayCode { get; set; }			
		[LWMeta(false)]				
		public virtual long? MemberRewardID { get; set; }			
		[LWMeta(false,50)]				
		public virtual string FirstName { get; set; }			
		[LWMeta(false,50)]				
		public virtual string LastName { get; set; }			
		[LWMeta(false,100)]				
		public virtual string AddressLineOne { get; set; }			
		[LWMeta(false,100)]				
		public virtual string AddressLineTwo { get; set; }			
		[LWMeta(false,50)]				
		public virtual string City { get; set; }			
		[LWMeta(false,50)]				
		public virtual string StateOrProvince { get; set; }			
		[LWMeta(false,25)]				
		public virtual string ZipOrPostalCode { get; set; }			
		[LWMeta(false,50)]				
		public virtual string Country { get; set; }			
		[LWMeta(false)]				
		public virtual bool? AddressMailable { get; set; }			
		[LWMeta(false)]				
		public virtual DateTime? DirectMailOptInDate { get; set; }			
		[LWMeta(false,20)]				
		public virtual string LanguagePreference { get; set; }			
		[LWMeta(false,100)]				
		public virtual string RewardTier { get; set; }			
		[LWMeta(false,20)]				
		public virtual string LoyaltyNumber { get; set; }			
		[LWMeta(false,20)]				
		public virtual string HHKeyBarCode { get; set; }			
		[LWMeta(false)]				
		public virtual bool? IsUnderAge { get; set; }			
		[LWMeta(false)]				
		public virtual long? StartingPoints { get; set; }			
		[LWMeta(false)]				
		public virtual long? BasePointBalance { get; set; }			
		[LWMeta(false)]				
		public virtual long? BonusPointBalance { get; set; }			
		[LWMeta(false,100)]				
		public virtual string RewardPartNumber { get; set; }			
		[LWMeta(false,50)]				
		public virtual string BarCode { get; set; }			
		[LWMeta(false,10)]				
		public virtual string BaseLoyaltyBrand { get; set; }			
		[LWMeta(false)]				
		public virtual long? PurchasedAEBrand { get; set; }			
		[LWMeta(false)]				
		public virtual long? PurchasedAerieBrand { get; set; }			
		[LWMeta(false)]				
		public virtual long? PurchasedKidsBrand { get; set; }			
		[LWMeta(false,50)]				
		public virtual string RewardType { get; set; }			
		[LWMeta(false)]				
		public virtual long? ParentRewardId { get; set; }			
		[LWMeta(false)]				
		public virtual bool? DirectMailOptIn { get; set; }			
		#endregion				
	}
}
