//------------------------------------------------------------------------------
// <autogenerated>
//     This code was generated by LoyaltyWare.
//
//     Changes to this file may cause incorrect behavior and will be lost if 
//     the code is regenerated.
// </autogenerated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;

using Brierley.LoyaltyWare.ClientLib;
//using Brierley.LoyaltyWare.ClientLib.DomainModel;
using Brierley.LoyaltyWare.ClientLib.DomainModel.Framework;

namespace Brierley.LoyaltyWare.ClientLib.DomainModel.Client
{
	public class MemberRewardInfoStruct
	{							    											    
		#region Properties
		[LWMeta(true)]        								
		public virtual long MemberRewardID { get; set; }			
		[LWMeta(true)]        								
		public virtual long RewardDefID { get; set; }			
		[LWMeta(false,0)]        								
		public virtual string FPOrderNumber { get; set; }			
		[LWMeta(false,0)]        								
		public virtual string CertificateNumber { get; set; }			
		[LWMeta(false)]        								
		public virtual decimal? AvailableBalance { get; set; }			
		[LWMeta(false)]        								
		public virtual DateTime? DateIssued { get; set; }			
		[LWMeta(false)]        								
		public virtual DateTime? ExpirationDate { get; set; }			
		[LWMeta(false)]        								
		public virtual DateTime? FulfillmentDate { get; set; }			
		[LWMeta(false)]        								
		public virtual DateTime? RedemptionDate { get; set; }			
		[LWMeta(false,0)]        								
		public virtual string OrderStatus { get; set; }			
		[LWMeta(false,0)]        								
		public virtual string TrackingUrl { get; set; }			
		[LWMeta(false,0)]        								
		public virtual string TrackingNumber { get; set; }			
		#endregion				
	}
}
