//------------------------------------------------------------------------------
// <autogenerated>
//     This code was generated by LoyaltyWare.
//
//     Changes to this file may cause incorrect behavior and will be lost if 
//     the code is regenerated.
// </autogenerated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;

using Brierley.LoyaltyWare.ClientLib;
using Brierley.LoyaltyWare.ClientLib.DomainModel;

namespace Brierley.LoyaltyWare.ClientLib.DomainModel.Client
{
	public class MemberBraPromoSummary : LWClientDataObject
	{							    											    
		#region Properties
		[LWMeta(false)]				
		public virtual DateTime? BraFirstPurchaseDate { get; set; }			
		[LWMeta(false)]				
		public virtual int? BraLifeTimeBalance { get; set; }			
		[LWMeta(false)]				
		public virtual int? BraRollingBalance { get; set; }			
		[LWMeta(false)]				
		public virtual DateTime? JeansFirstPurchaseDate { get; set; }			
		[LWMeta(false)]				
		public virtual int? JeansLifeTimeBalance { get; set; }			
		[LWMeta(false)]				
		public virtual int? JeansRollingBalance { get; set; }			
		[LWMeta(false)]				
		public virtual long? CurrentBalance { get; set; }			
		[LWMeta(false)]				
		public virtual long? FulfillmentBalance { get; set; }			
		[LWMeta(false)]				
		public virtual long? TotalPurchased { get; set; }			
		[LWMeta(false)]				
		public virtual long? TotalReturned { get; set; }			
		#endregion				
	}
}
