//------------------------------------------------------------------------------
// <autogenerated>
//     This code was generated by LoyaltyWare.
//
//     Changes to this file may cause incorrect behavior and will be lost if 
//     the code is regenerated.
// </autogenerated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;

using Brierley.LoyaltyWare.ClientLib;
using Brierley.LoyaltyWare.ClientLib.DomainModel;

namespace Brierley.LoyaltyWare.ClientLib.DomainModel.Client
{
	public class MemberBraPromoCertSummary : LWClientDataObject
	{							    											    
		#region Properties
		[LWMeta(false)]				
		public virtual DateTime? FulfillmentPeriod { get; set; }			
		[LWMeta(false)]				
		public virtual long? ReasonCode { get; set; }			
		[LWMeta(false)]				
		public virtual long? NumCertsAwarded { get; set; }			
		[LWMeta(false)]				
		public virtual long? NumberCertsRedeemed { get; set; }			
		[LWMeta(false)]				
		public virtual DateTime? ProcessDate { get; set; }			
		[LWMeta(false)]				
		public virtual DateTime? InHomeDate { get; set; }			
		[LWMeta(false)]				
		public virtual DateTime? RedemptionDate { get; set; }			
		#endregion				
	}
}
