//------------------------------------------------------------------------------
// <autogenerated>
//     This code was generated by LoyaltyWare.
//
//     Changes to this file may cause incorrect behavior and will be lost if 
//     the code is regenerated.
// </autogenerated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;

using Brierley.LoyaltyWare.ClientLib;
//using Brierley.LoyaltyWare.ClientLib.DomainModel;
using Brierley.LoyaltyWare.ClientLib.DomainModel.Framework;

namespace Brierley.LoyaltyWare.ClientLib.DomainModel.Client
{
	public class MergeMembersIn
	{							    											    
		#region Properties
		[LWMeta(true,0)]        								
		public virtual string MemberIdentity1 { get; set; }			
		[LWMeta(true,0)]        								
		public virtual string MemberIdentity2 { get; set; }			
		[LWMeta(true,150)]        								
		public virtual string LoyaltyEvent { get; set; }			
		[LWMeta(true,150)]        								
		public virtual string LoyaltyCurrency { get; set; }			
		[LWMeta(false)]        								
		public virtual DateTime? ExpirationDate { get; set; }			
		[LWMeta(false)]        								
		public virtual MemberMergeOptionsStruct MemberMergeOptions { get; set; }			
		#endregion				
	}
}
