//------------------------------------------------------------------------------
// <autogenerated>
//     This code was generated by LoyaltyWare.
//
//     Changes to this file may cause incorrect behavior and will be lost if 
//     the code is regenerated.
// </autogenerated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;

using Brierley.LoyaltyWare.ClientLib;
//using Brierley.LoyaltyWare.ClientLib.DomainModel;
using Brierley.LoyaltyWare.ClientLib.DomainModel.Framework;

namespace Brierley.LoyaltyWare.ClientLib.DomainModel.Client
{
	public class PointsHistoryStruct
	{							    											    
		#region Properties
		[LWMeta(true)]        								
		public virtual decimal CurrencyAmount { get; set; }			
		[LWMeta(true,0)]        								
		public virtual string PointTxnType { get; set; }			
		[LWMeta(true,0)]        								
		public virtual string LoyaltyEvent { get; set; }			
		[LWMeta(true,0)]        								
		public virtual string LoyaltyCurrency { get; set; }			
		[LWMeta(true)]        								
		public virtual DateTime TxnDate { get; set; }			
		[LWMeta(false,0)]        								
		public virtual string OwnerType { get; set; }			
		[LWMeta(false)]        								
		public virtual long? OwnerId { get; set; }			
		[LWMeta(false)]        								
		public virtual long? RowKey { get; set; }			
		[LWMeta(false,0)]        								
		public virtual string PromoCode { get; set; }			
		[LWMeta(false)]        								
		public virtual DateTime? ExpirationDate { get; set; }			
		[LWMeta(false,500)]        								
		public virtual string Notes { get; set; }			
		#endregion				
	}
}
