//------------------------------------------------------------------------------
// <autogenerated>
//     This code was generated by LoyaltyWare.
//
//     Changes to this file may cause incorrect behavior and will be lost if 
//     the code is regenerated.
// </autogenerated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;

using Brierley.LoyaltyWare.ClientLib;
//using Brierley.LoyaltyWare.ClientLib.DomainModel;
using Brierley.LoyaltyWare.ClientLib.DomainModel.Framework;

namespace Brierley.LoyaltyWare.ClientLib.DomainModel.Client
{
	public class ProductVariantStruct
	{							    											    
		#region Properties
		[LWMeta(true)]        								
		public virtual long ProductVariantID { get; set; }			
		[LWMeta(true,0)]        								
		public virtual string Description { get; set; }			
		[LWMeta(false,0)]        								
		public virtual string PartNumber { get; set; }			
		[LWMeta(false)]        								
		public virtual int? Quantity { get; set; }			
		[LWMeta(false)]        								
		public virtual int? VariantOrder { get; set; }			
		#endregion				
	}
}
