//------------------------------------------------------------------------------
// <autogenerated>
//     This code was generated by LoyaltyWare.
//
//     Changes to this file may cause incorrect behavior and will be lost if 
//     the code is regenerated.
// </autogenerated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;

using Brierley.LoyaltyWare.ClientLib;
using Brierley.LoyaltyWare.ClientLib.DomainModel;

namespace Brierley.LoyaltyWare.ClientLib.DomainModel.Client
{
	public class RefProduct : LWClientDataObject
	{							    											    
		#region Properties
		[LWMeta(false,50)]				
		public virtual string BrandID { get; set; }			
		[LWMeta(false,100)]				
		public virtual string ProductSKU { get; set; }			
		[LWMeta(false,50)]				
		public virtual string ClassCode { get; set; }			
		[LWMeta(false,100)]				
		public virtual string ClassDescription { get; set; }			
		[LWMeta(false,50)]				
		public virtual string StyleCode { get; set; }			
		[LWMeta(false,100)]				
		public virtual string StyleDescription { get; set; }			
		[LWMeta(false,50)]				
		public virtual string DeptCode { get; set; }			
		[LWMeta(false,100)]				
		public virtual string DepDescription { get; set; }			
		[LWMeta(false,50)]				
		public virtual string DivisionCode { get; set; }			
		[LWMeta(false,100)]				
		public virtual string DivisionDescription { get; set; }			
		[LWMeta(false,50)]				
		public virtual string CompanyCode { get; set; }			
		[LWMeta(false,100)]				
		public virtual string CompanyDescription { get; set; }			
		[LWMeta(false,100)]				
		public virtual string ProductDescription { get; set; }			
		#endregion				
	}
}
