//------------------------------------------------------------------------------
// <autogenerated>
//     This code was generated by LoyaltyWare.
//
//     Changes to this file may cause incorrect behavior and will be lost if 
//     the code is regenerated.
// </autogenerated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;

using Brierley.LoyaltyWare.ClientLib;
using Brierley.LoyaltyWare.ClientLib.DomainModel;

namespace Brierley.LoyaltyWare.ClientLib.DomainModel.Client
{
	public class RefVendors : LWClientDataObject
	{							    											    
		#region Properties
		[LWMeta(true,255)]				
		public virtual string VendorId { get; set; }			
		[LWMeta(true,255)]				
		public virtual string VendorName { get; set; }			
		#endregion				
	}
}
