//------------------------------------------------------------------------------
// <autogenerated>
//     This code was generated by LoyaltyWare.
//
//     Changes to this file may cause incorrect behavior and will be lost if 
//     the code is regenerated.
// </autogenerated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;

using Brierley.LoyaltyWare.ClientLib;
using Brierley.LoyaltyWare.ClientLib.DomainModel;

namespace Brierley.LoyaltyWare.ClientLib.DomainModel.Client
{
	public class RewardBarCodes : LWClientDataObject
	{							    											    
		#region Properties
		[LWMeta(false)]				
		public virtual DateTime? EffectiveStartDate { get; set; }			
		[LWMeta(true,25)]				
		public virtual string TypeCode { get; set; }			
		[LWMeta(true,50)]				
		public virtual string BarCode { get; set; }			
		[LWMeta(true)]				
		public virtual int Status { get; set; }			
		[LWMeta(false)]				
		public virtual DateTime? EffectiveEndDate { get; set; }			
		#endregion				
	}
}
