//------------------------------------------------------------------------------
// <autogenerated>
//     This code was generated by LoyaltyWare.
//
//     Changes to this file may cause incorrect behavior and will be lost if 
//     the code is regenerated.
// </autogenerated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;

using Brierley.LoyaltyWare.ClientLib;
using Brierley.LoyaltyWare.ClientLib.DomainModel;

namespace Brierley.LoyaltyWare.ClientLib.DomainModel.Client
{
	public class SocialMediaPost : LWClientDataObject
	{							    											    
		#region Properties
		[LWMeta(false)]				
		public virtual int? CommentCount { get; set; }			
		[LWMeta(false)]				
		public virtual int? Following { get; set; }			
		[LWMeta(false)]				
		public virtual int? Followers { get; set; }			
		[LWMeta(false)]				
		public virtual DateTime? PublishDate { get; set; }			
		[LWMeta(false)]				
		public virtual int? ViewCount { get; set; }			
		[LWMeta(false,500)]				
		public virtual string Content { get; set; }			
		[LWMeta(false,25)]				
		public virtual string ArticleID { get; set; }			
		[LWMeta(false,500)]				
		public virtual string Headline { get; set; }			
		[LWMeta(false,255)]				
		public virtual string ArticleURL { get; set; }			
		[LWMeta(false,255)]				
		public virtual string MediaProvider { get; set; }			
		#endregion				
	}
}
