//------------------------------------------------------------------------------
// <autogenerated>
//     This code was generated by LoyaltyWare.
//
//     Changes to this file may cause incorrect behavior and will be lost if 
//     the code is regenerated.
// </autogenerated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;

using Brierley.LoyaltyWare.ClientLib;
using Brierley.LoyaltyWare.ClientLib.DomainModel;

namespace Brierley.LoyaltyWare.ClientLib.DomainModel.Client
{
	public class TlogAudit : LWClientDataObject
	{							    											    
		#region Properties
		[LWMeta(false)]				
		public virtual int? AEStoreNumber { get; set; }			
		[LWMeta(false)]				
		public virtual int? AETransactionCount { get; set; }			
		[LWMeta(false)]				
		public virtual int? AELoyaltyCount { get; set; }			
		[LWMeta(false)]				
		public virtual int? BPStoreNumber { get; set; }			
		[LWMeta(false)]				
		public virtual int? BPTransactionCount { get; set; }			
		[LWMeta(false)]				
		public virtual int? BPLoyaltyCount { get; set; }			
		#endregion				
	}
}
