//------------------------------------------------------------------------------
// <autogenerated>
//     This code was generated by LoyaltyWare.
//
//     Changes to this file may cause incorrect behavior and will be lost if 
//     the code is regenerated.
// </autogenerated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;

using Brierley.LoyaltyWare.ClientLib;
using Brierley.LoyaltyWare.ClientLib.DomainModel;

namespace Brierley.LoyaltyWare.ClientLib.DomainModel.Client
{
	public class TxnDetailItem : LWClientDataObject
	{							    											    
		#region Properties
		[LWMeta(false,50)]				
		public virtual string DtlClassCode { get; set; }			
		[LWMeta(false,10)]				
		public virtual string ReasonCode { get; set; }			
		[LWMeta(false,50)]				
		public virtual string TxnHeaderId { get; set; }			
		[LWMeta(false)]				
		public virtual DateTime? TxnDate { get; set; }			
		[LWMeta(false)]				
		public virtual long? TxnStoreId { get; set; }			
		[LWMeta(true,50)]				
		public virtual string TxnDetailId { get; set; }			
		[LWMeta(false)]				
		public virtual int? DtlItemLineNbr { get; set; }			
		[LWMeta(false)]				
		public virtual int? DtlProductId { get; set; }			
		[LWMeta(false)]				
		public virtual int? DtlTypeId { get; set; }			
		[LWMeta(false)]				
		public virtual int? DtlActionId { get; set; }			
		[LWMeta(true)]				
		public virtual decimal DtlRetailAmount { get; set; }			
		[LWMeta(true)]				
		public virtual decimal DtlSaleAmount { get; set; }			
		[LWMeta(false)]				
		public virtual int? DtlQuantity { get; set; }			
		[LWMeta(true)]				
		public virtual decimal DtlDiscountAmount { get; set; }			
		[LWMeta(true)]				
		public virtual int DtlClearanceItem { get; set; }			
		#endregion				
	}
}
