//------------------------------------------------------------------------------
// <autogenerated>
//     This code was generated by LoyaltyWare.
//
//     Changes to this file may cause incorrect behavior and will be lost if 
//     the code is regenerated.
// </autogenerated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;

using Brierley.LoyaltyWare.ClientLib;
using Brierley.LoyaltyWare.ClientLib.DomainModel;

namespace Brierley.LoyaltyWare.ClientLib.DomainModel.Client
{
	public class TxnRewardRedeem : LWClientDataObject
	{							    											    
		#region Properties
		[LWMeta(true,50)]				
		public virtual string TxnHeaderId { get; set; }			
		[LWMeta(true)]				
		public virtual DateTime TxnDate { get; set; }			
		[LWMeta(false,50)]				
		public virtual string TxnDetailId { get; set; }			
		[LWMeta(false)]				
		public virtual int? ProgramId { get; set; }			
		[LWMeta(false,3)]				
		public virtual string CertificateRedeemType { get; set; }			
		[LWMeta(false,50)]				
		public virtual string CertificateCode { get; set; }			
		[LWMeta(false)]				
		public virtual decimal? CertificateDiscountAmount { get; set; }			
		#endregion				
	}
}
