//------------------------------------------------------------------------------
// <autogenerated>
//     This code was generated by LoyaltyWare.
//
//     Changes to this file may cause incorrect behavior and will be lost if 
//     the code is regenerated.
// </autogenerated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;

using Brierley.LoyaltyWare.ClientLib;
//using Brierley.LoyaltyWare.ClientLib.DomainModel;
using Brierley.LoyaltyWare.ClientLib.DomainModel.Framework;

namespace Brierley.LoyaltyWare.ClientLib.DomainModel.Client
{
	public class TxnStoreInfoStruct
	{							    											    
		#region Properties
		[LWMeta(false,0)]        								
		public virtual string StoreName { get; set; }			
		[LWMeta(false,0)]        								
		public virtual string StoreNumber { get; set; }			
		[LWMeta(false,0)]        								
		public virtual string City { get; set; }			
		[LWMeta(false,0)]        								
		public virtual string State { get; set; }			
		#endregion				
	}
}
