//------------------------------------------------------------------------------
// <autogenerated>
//     This code was generated by LoyaltyWare.
//
//     Changes to this file may cause incorrect behavior and will be lost if 
//     the code is regenerated.
// </autogenerated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;

using Brierley.LoyaltyWare.ClientLib;
using Brierley.LoyaltyWare.ClientLib.DomainModel;

namespace Brierley.LoyaltyWare.ClientLib.DomainModel.Client
{
	public class TxnTender : LWClientDataObject
	{							    											    
		#region Properties
		[LWMeta(false)]				
		public virtual long? RoundedAmount { get; set; }			
		[LWMeta(false)]				
		public virtual DateTime? TxnDate { get; set; }			
		[LWMeta(false)]				
		public virtual int? TxnStoreId { get; set; }			
		[LWMeta(true,50)]				
		public virtual string TxnTenderId { get; set; }			
		[LWMeta(true,50)]				
		public virtual string TxnHeaderId { get; set; }			
		[LWMeta(true)]				
		public virtual int TenderType { get; set; }			
		[LWMeta(true)]				
		public virtual decimal TenderAmount { get; set; }			
		[LWMeta(false,20)]				
		public virtual string TenderCurrency { get; set; }			
		[LWMeta(true)]				
		public virtual decimal TenderTaxAmount { get; set; }			
		[LWMeta(true)]				
		public virtual decimal TenderTaxRate { get; set; }			
		#endregion				
	}
}
